-- ==========================================================================
-- Haryana STF Demo — Drug Trafficking & Narcotics Intelligence
-- ==========================================================================
-- Scenario: STF Haryana monitoring drug trafficking along the Punjab-Haryana
-- corridor, chitta/heroin epidemic, synthetic drugs, poppy husk smuggling,
-- and mule networks across Panchkula, Ambala, and Karnal districts.
--
-- Context: Haryana is a major transit corridor for drugs from Punjab to Delhi.
-- STF Haryana conducts anti-narcotics ops across the state. Chitta (adulterated
-- heroin) epidemic in Ambala-Karnal belt. Cross-border smuggling via Punjab.
-- NDPS Act enforcement, NCB coordination, BSF border operations.
--
-- Org: org_cyber (reusing existing org for demo user)
-- User: demo_cyber@anveshak.local (existing)
--
-- Idempotent: all INSERTs use ON CONFLICT DO NOTHING.
-- Run: docker exec -i anveshak-postgres-1 psql -U anveshak -d anveshak < scripts/seed_haryana_demo.sql
-- ==========================================================================

-- ==========================================================================
-- 1. Topic
-- ==========================================================================
INSERT INTO topics (
    id, name, keywords, signal_threshold, identifier_signal_threshold,
    status, languages, credibility_min,
    labels, created_at, updated_at, org_id
) VALUES (
    'hr-stf-001',
    'Haryana STF Narcotics Intelligence',
    ARRAY['drug trafficking', 'chitta', 'heroin', 'synthetic drugs', 'poppy husk',
          'NDPS', 'narcotics', 'mule', 'Punjab corridor', 'Panchkula',
          'Ambala', 'Karnal'],
    2, 2, 'active', ARRAY['en', 'hi'], 20.0,
    '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb,
    NOW() - INTERVAL '30 days', NOW(), 'org_cyber'
) ON CONFLICT (id) DO NOTHING;

-- ==========================================================================
-- 2. Sources (13)
-- ==========================================================================
INSERT INTO sources (id, name, url_or_handle, platform, credibility_score, is_active, health_status, labels, created_at, updated_at, org_id) VALUES
    -- ── RSS / Web News Sources (Haryana + National) ──
    ('hr-src-01', 'Tribune India - Haryana',       'https://www.tribuneindia.com/rss/feed/haryana',    'rss', 82.0, true, 'healthy', '{"classification":"OPEN","domain":"narcotics","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('hr-src-02', 'Dainik Jagran - Haryana',       'https://www.jagran.com/rss/haryana-news.xml',     'rss', 75.0, true, 'healthy', '{"classification":"OPEN","domain":"narcotics","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('hr-src-03', 'Hindustan Times - Chandigarh',  'https://www.hindustantimes.com/feeds/rss/chandigarh/rssfeed.xml', 'rss', 80.0, true, 'healthy', '{"classification":"OPEN","domain":"narcotics","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('hr-src-04', 'Amar Ujala - Haryana',          'https://www.amarujala.com/rss/haryana.xml',       'rss', 72.0, true, 'healthy', '{"classification":"OPEN","domain":"narcotics","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('hr-src-05', 'Indian Express - Haryana',      'https://indianexpress.com/section/cities/chandigarh/feed/', 'rss', 78.0, true, 'healthy', '{"classification":"OPEN","domain":"narcotics","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),

    -- ── Telegram Sources (drug trafficking channels) ──
    ('hr-src-06', 'Punjab Drug Watch',             'punjab_drug_watch',         'telegram', 20.0, true, 'healthy', '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('hr-src-07', 'Haryana Crime Updates',         'haryana_crime_updates',     'telegram', 25.0, true, 'healthy', '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('hr-src-08', 'NCR Underground',               'ncr_underground_intel',     'telegram', 15.0, true, 'healthy', '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('hr-src-09', 'Chitta Alert Network',          'chitta_alert_hrpb',         'telegram', 12.0, true, 'healthy', '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),

    -- ── Web (official sources) ──
    ('hr-src-10', 'Haryana Police Official',       'https://haryanapolice.gov.in',                    'web',  90.0, true, 'healthy', '{"classification":"OPEN","domain":"narcotics","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('hr-src-11', 'NCB India',                     'https://narcoticsindia.nic.in',                   'web',  92.0, true, 'healthy', '{"classification":"OPEN","domain":"narcotics","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),

    -- ── YouTube ──
    ('hr-src-12', 'Haryana Police Press',          'haryana_police_official',   'youtube',  85.0, true, 'healthy', '{"classification":"OPEN","domain":"narcotics","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),

    -- ── Dark Web ──
    ('hr-src-13', 'Ahmia Onion Search',            'http://juhanurmihxlp77nkq76byazcldy2hlmovfu2epvl5ankdibsot4csyd.onion/', 'darkweb', 5.0, true, 'healthy', '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber')
ON CONFLICT (id) DO NOTHING;

-- org_sources visibility
INSERT INTO org_sources (org_id, source_id) VALUES
    ('org_cyber','hr-src-01'),('org_cyber','hr-src-02'),('org_cyber','hr-src-03'),
    ('org_cyber','hr-src-04'),('org_cyber','hr-src-05'),('org_cyber','hr-src-06'),
    ('org_cyber','hr-src-07'),('org_cyber','hr-src-08'),('org_cyber','hr-src-09'),
    ('org_cyber','hr-src-10'),('org_cyber','hr-src-11'),('org_cyber','hr-src-12'),
    ('org_cyber','hr-src-13')
ON CONFLICT DO NOTHING;

-- topic_sources
INSERT INTO topic_sources (topic_id, source_id) VALUES
    ('hr-stf-001','hr-src-01'),('hr-stf-001','hr-src-02'),('hr-stf-001','hr-src-03'),
    ('hr-stf-001','hr-src-04'),('hr-stf-001','hr-src-05'),('hr-stf-001','hr-src-06'),
    ('hr-stf-001','hr-src-07'),('hr-stf-001','hr-src-08'),('hr-stf-001','hr-src-09'),
    ('hr-stf-001','hr-src-10'),('hr-stf-001','hr-src-11'),('hr-stf-001','hr-src-12'),
    ('hr-stf-001','hr-src-13')
ON CONFLICT DO NOTHING;

-- ==========================================================================
-- 3. Narrative Clusters (5)
-- ==========================================================================
INSERT INTO narrative_clusters (id, topic_id, label, item_count, independent_source_count, executive_summary, created_at, updated_at, labels) VALUES
    ('hr-cl-01', 'hr-stf-001', 'Punjab-Haryana Drug Corridor Seizures', 12, 4,
     'Multiple seizures along the NH-44 and NH-152 corridors connecting Punjab to Delhi via Ambala and Karnal. STF and BSF operations intercepting heroin and chitta shipments at toll plazas and border checkpoints.',
     NOW()-INTERVAL '25 days', NOW(), '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
    ('hr-cl-02', 'hr-stf-001', 'Chitta Epidemic in Ambala-Karnal Belt', 10, 3,
     'Rising chitta (adulterated heroin) addiction among youth in Ambala and Karnal districts. Reports of overdose deaths, community protests, and demands for government intervention. Rehabilitation centers overwhelmed.',
     NOW()-INTERVAL '20 days', NOW(), '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
    ('hr-cl-03', 'hr-stf-001', 'STF Operations and Major Arrests', 10, 4,
     'STF Haryana conducting targeted operations against drug networks. Multiple arrests of inter-state drug suppliers, seizure of synthetic drugs, cash, and vehicles. Coordination with Punjab Police and NCB.',
     NOW()-INTERVAL '18 days', NOW(), '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
    ('hr-cl-04', 'hr-stf-001', 'Cross-Border Smuggling Networks via Punjab', 8, 3,
     'Intelligence reports of organized smuggling networks operating across Punjab-Haryana border. Afghan heroin routed through Pakistan-Punjab-Haryana-Delhi. Telegram channels used for coordination.',
     NOW()-INTERVAL '12 days', NOW(), '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
    ('hr-cl-05', 'hr-stf-001', 'Youth Anti-Drug Movement and Rehabilitation', 8, 3,
     'Growing anti-drug movement led by youth organizations and NGOs in Haryana. Demand for more rehabilitation centers, NDPS court fast-tracking, and community policing. Social media campaigns trending.',
     NOW()-INTERVAL '8 days', NOW(), '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ==========================================================================
-- 4. Content Items (50 items across 5 clusters, 30 days)
-- ==========================================================================

-- ── Cluster 1: Punjab-Haryana Drug Corridor Seizures (12 items) ──
INSERT INTO content_items (id, topic_id, source_id, url, raw_text, clean_text, content_hash, language, captured_at, credibility_score_at_capture, narrative_cluster_id, labels, created_at, updated_at, org_id) VALUES
('hr-ci-01','hr-stf-001','hr-src-01','https://tribuneindia.com/haryana-drug-seizure-nh44','Major drug seizure on NH-44 near Ambala','STF Haryana seizes 15 kg heroin worth Rs 75 crore from a truck on NH-44 near Ambala Cantt toll plaza. Two Punjab residents arrested. Consignment was being transported from Amritsar to Delhi via Haryana. STF acted on intelligence input from NCB.', md5('hr-ci-01'),'en',NOW()-INTERVAL '28 days',82.0,'hr-cl-01','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Tribune India","author_id":"hr-src-01","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.5,"label":"negative"},"keywords":["heroin","seizure","NH-44","Ambala","STF","NCB"]}'::jsonb,NOW()-INTERVAL '28 days',NOW(),'org_cyber'),
('hr-ci-02','hr-stf-001','hr-src-03','https://hindustantimes.com/chandigarh/karnal-poppy-husk','Poppy husk worth Rs 2 crore seized in Karnal','Haryana Police STF intercepts truck carrying 500 kg poppy husk (bhukki) near Karnal bypass. Driver fled, abandoned vehicle. Consignment traced to Rajasthan via GPS tracking. Second major seizure this month on NH-44 corridor.', md5('hr-ci-02'),'en',NOW()-INTERVAL '27 days',80.0,'hr-cl-01','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Hindustan Times","author_id":"hr-src-03","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.45,"label":"negative"},"keywords":["poppy husk","Karnal","STF","Rajasthan","NH-44"]}'::jsonb,NOW()-INTERVAL '27 days',NOW(),'org_cyber'),
('hr-ci-03','hr-stf-001','hr-src-06','https://t.me/punjab_drug_watch/234','New route via Patiala-Panchkula bypass','ALERT: Smugglers using new route via Patiala-Panchkula bypass road to avoid NH-44 checkpoints. Smaller quantities in private cars instead of trucks. Contact for info: +91-98765-11111.', md5('hr-ci-03'),'en',NOW()-INTERVAL '26 days',20.0,'hr-cl-01','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@punjab_drug_watch","author_id":"punjab_drug_watch","engagement":{"likes":12,"comments":34,"shares":0,"views":560,"forwards":15},"sentiment":{"compound":-0.7,"label":"negative"},"keywords":["new route","Patiala","Panchkula","bypass","smugglers"]}'::jsonb,NOW()-INTERVAL '26 days',NOW(),'org_cyber'),
('hr-ci-04','hr-stf-001','hr-src-07','https://t.me/haryana_crime_updates/567','Toll plaza checkpoint surprise raid','STF conducts surprise raid at Shahabad toll plaza on NH-152. 3 vehicles checked, 2 kg synthetic drugs recovered from hidden compartment. Modus operandi: drugs concealed in modified fuel tank.', md5('hr-ci-04'),'en',NOW()-INTERVAL '25 days',25.0,'hr-cl-01','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@haryana_crime_updates","author_id":"haryana_crime_updates","engagement":{"likes":23,"comments":45,"shares":0,"views":890,"forwards":18},"sentiment":{"compound":-0.55,"label":"negative"},"keywords":["STF","raid","Shahabad","synthetic drugs","toll plaza"]}'::jsonb,NOW()-INTERVAL '25 days',NOW(),'org_cyber'),
('hr-ci-05','hr-stf-001','hr-src-02','https://jagran.com/haryana-drug-corridor-analysis','Drug corridor analysis: Punjab to Delhi via Haryana','Dainik Jagran investigative report: Haryana has become the primary transit corridor for drugs from Punjab to Delhi-NCR. NH-44 and NH-152 are the main arteries. Over 200 kg narcotics seized in last 6 months. STF sources say for every seizure, 10x gets through.', md5('hr-ci-05'),'en',NOW()-INTERVAL '23 days',75.0,'hr-cl-01','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Dainik Jagran","author_id":"hr-src-02","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.6,"label":"negative"},"keywords":["drug corridor","Punjab","Delhi","NH-44","NH-152","transit"]}'::jsonb,NOW()-INTERVAL '23 days',NOW(),'org_cyber'),
('hr-ci-06','hr-stf-001','hr-src-08','https://t.me/ncr_underground_intel/89','Delhi receiver network exposed','NCR network: Delhi-based receiver identified. Uses Telegram handles @delhimaaldrop and @ncr_supply_786. Coordinates with Punjab suppliers via encrypted channels. Drops in Sonipat and Panipat. Phone: +91-98765-22222.', md5('hr-ci-06'),'en',NOW()-INTERVAL '22 days',15.0,'hr-cl-01','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@ncr_underground_intel","author_id":"ncr_underground_intel","engagement":{"likes":5,"comments":15,"shares":0,"views":340,"forwards":8},"sentiment":{"compound":-0.75,"label":"negative"},"keywords":["Delhi","receiver","Telegram","Sonipat","Panipat","network"]}'::jsonb,NOW()-INTERVAL '22 days',NOW(),'org_cyber'),
('hr-ci-07','hr-stf-001','hr-src-04','https://amarujala.com/haryana-bsf-drug-seizure','BSF seizes heroin at Fazilka-Sirsa border','BSF troops seized 5 kg heroin worth Rs 25 crore near Fazilka-Sirsa border sector. Drone was used to drop narcotics from Pakistan side. Second drone-based smuggling attempt this month.', md5('hr-ci-07'),'en',NOW()-INTERVAL '20 days',72.0,'hr-cl-01','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Amar Ujala","author_id":"hr-src-04","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.65,"label":"negative"},"keywords":["BSF","heroin","Fazilka","Sirsa","drone","Pakistan"]}'::jsonb,NOW()-INTERVAL '20 days',NOW(),'org_cyber'),
('hr-ci-08','hr-stf-001','hr-src-05','https://indianexpress.com/haryana-stf-network-busted','Inter-state drug network busted by STF','Indian Express: STF Haryana busts inter-state drug network operating across Punjab, Haryana, and Rajasthan. 8 arrested including kingpin from Amritsar. Rs 50 crore worth narcotics seized over 3-month operation. Network used hawala for payments.', md5('hr-ci-08'),'en',NOW()-INTERVAL '18 days',78.0,'hr-cl-01','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Indian Express","author_id":"hr-src-05","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.5,"label":"negative"},"keywords":["STF","network busted","Punjab","Rajasthan","hawala","kingpin"]}'::jsonb,NOW()-INTERVAL '18 days',NOW(),'org_cyber'),
('hr-ci-09','hr-stf-001','hr-src-09','https://t.me/chitta_alert_hrpb/45','Chitta supply line from Ludhiana','WARNING: New chitta supply line established from Ludhiana to Ambala via Rajpura. Small-time peddlers using auto-rickshaws. Contact +91-98765-11111 for updates. Price drop indicates increased supply.', md5('hr-ci-09'),'en',NOW()-INTERVAL '16 days',12.0,'hr-cl-01','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@chitta_alert_hrpb","author_id":"chitta_alert_hrpb","engagement":{"likes":8,"comments":20,"shares":0,"views":430,"forwards":10},"sentiment":{"compound":-0.8,"label":"negative"},"keywords":["chitta","Ludhiana","Ambala","Rajpura","supply line","peddlers"]}'::jsonb,NOW()-INTERVAL '16 days',NOW(),'org_cyber'),
('hr-ci-10','hr-stf-001','hr-src-10','https://haryanapolice.gov.in/press-release-drug-ops','Haryana Police press release: Q2 drug operations','Official press release: Haryana Police STF conducted 142 operations in Q2 2026. Total seizures: 85 kg heroin, 1200 kg poppy husk, 15 kg synthetic drugs. 234 persons arrested under NDPS Act. Conviction rate 78%.', md5('hr-ci-10'),'en',NOW()-INTERVAL '14 days',90.0,'hr-cl-01','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Haryana Police","author_id":"hr-src-10","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.1,"label":"neutral"},"keywords":["STF","operations","seizures","heroin","NDPS","conviction"]}'::jsonb,NOW()-INTERVAL '14 days',NOW(),'org_cyber'),
('hr-ci-11','hr-stf-001','hr-src-06','https://t.me/punjab_drug_watch/250','Ambala railway station interception','Drug mule intercepted at Ambala Cantt railway station. 1.5 kg heroin found in specially stitched jacket lining. Mule was traveling from Jalandhar to Delhi on Shatabdi Express. Contact: +91-98765-22222.', md5('hr-ci-11'),'en',NOW()-INTERVAL '12 days',20.0,'hr-cl-01','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@punjab_drug_watch","author_id":"punjab_drug_watch","engagement":{"likes":15,"comments":28,"shares":0,"views":670,"forwards":12},"sentiment":{"compound":-0.6,"label":"negative"},"keywords":["drug mule","Ambala","railway","heroin","Jalandhar","Delhi"]}'::jsonb,NOW()-INTERVAL '12 days',NOW(),'org_cyber'),
('hr-ci-12','hr-stf-001','hr-src-11','https://narcoticsindia.nic.in/haryana-coordination','NCB coordination meeting on Haryana drug menace','NCB convenes coordination meeting with Haryana STF, Punjab Police, and BSF. Focus on dismantling Afghan heroin pipeline through Punjab-Haryana corridor. Multi-agency task force proposed.', md5('hr-ci-12'),'en',NOW()-INTERVAL '10 days',92.0,'hr-cl-01','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"NCB India","author_id":"hr-src-11","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.2,"label":"negative"},"keywords":["NCB","coordination","STF","Punjab","BSF","Afghan heroin"]}'::jsonb,NOW()-INTERVAL '10 days',NOW(),'org_cyber'),

-- ── Cluster 2: Chitta Epidemic in Ambala-Karnal Belt (10 items) ──
('hr-ci-13','hr-stf-001','hr-src-01','https://tribuneindia.com/chitta-epidemic-ambala','Chitta claims 3 more lives in Ambala','Tribune India: Three youth from Ambala Sadar area die of chitta overdose within a week. Families blame easy availability and police inaction. Local MLA demands emergency measures. Hospital reports 50% rise in drug overdose cases.', md5('hr-ci-13'),'en',NOW()-INTERVAL '26 days',82.0,'hr-cl-02','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Tribune India","author_id":"hr-src-01","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.85,"label":"negative"},"keywords":["chitta","overdose","Ambala","youth","deaths","epidemic"]}'::jsonb,NOW()-INTERVAL '26 days',NOW(),'org_cyber'),
('hr-ci-14','hr-stf-001','hr-src-07','https://t.me/haryana_crime_updates/580','Karnal rehab center overwhelmed','Karnal district drug rehabilitation center overwhelmed — 200% capacity. Patients sleeping on floors. Most admissions are chitta users aged 18-25. Government funding inadequate. NGOs stepping in.', md5('hr-ci-14'),'en',NOW()-INTERVAL '24 days',25.0,'hr-cl-02','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@haryana_crime_updates","author_id":"haryana_crime_updates","engagement":{"likes":45,"comments":67,"shares":0,"views":1500,"forwards":22},"sentiment":{"compound":-0.7,"label":"negative"},"keywords":["Karnal","rehabilitation","chitta","youth","overcrowded"]}'::jsonb,NOW()-INTERVAL '24 days',NOW(),'org_cyber'),
('hr-ci-15','hr-stf-001','hr-src-03','https://hindustantimes.com/chandigarh/chitta-schools','Chitta reaches school gates in Ambala','Hindustan Times investigation: Chitta peddlers operating near school gates in Ambala and Karnal. Students as young as 15 being targeted. Parents form vigilante groups. Police promise crackdown but community skeptical.', md5('hr-ci-15'),'en',NOW()-INTERVAL '22 days',80.0,'hr-cl-02','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Hindustan Times","author_id":"hr-src-03","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.9,"label":"negative"},"keywords":["chitta","schools","Ambala","Karnal","peddlers","students"]}'::jsonb,NOW()-INTERVAL '22 days',NOW(),'org_cyber'),
('hr-ci-16','hr-stf-001','hr-src-09','https://t.me/chitta_alert_hrpb/50','Chitta price crash — supply surge','Chitta price crashed from Rs 5000/gram to Rs 2000/gram in Ambala. Indicates massive supply surge. New batch entering from Punjab. Quality also degrading — more adulterants, higher overdose risk.', md5('hr-ci-16'),'en',NOW()-INTERVAL '20 days',12.0,'hr-cl-02','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@chitta_alert_hrpb","author_id":"chitta_alert_hrpb","engagement":{"likes":10,"comments":25,"shares":0,"views":380,"forwards":14},"sentiment":{"compound":-0.75,"label":"negative"},"keywords":["chitta","price","supply","Ambala","Punjab","adulterants"]}'::jsonb,NOW()-INTERVAL '20 days',NOW(),'org_cyber'),
('hr-ci-17','hr-stf-001','hr-src-02','https://jagran.com/haryana-chitta-deaths-karnal','12 chitta deaths in Karnal in one month','Dainik Jagran: Karnal district records 12 deaths from chitta overdose in one month. CM orders inquiry. Health department sets up special detox ward. Opposition demands white paper on drug menace.', md5('hr-ci-17'),'en',NOW()-INTERVAL '18 days',75.0,'hr-cl-02','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Dainik Jagran","author_id":"hr-src-02","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.8,"label":"negative"},"keywords":["chitta","deaths","Karnal","CM","inquiry","detox"]}'::jsonb,NOW()-INTERVAL '18 days',NOW(),'org_cyber'),
('hr-ci-18','hr-stf-001','hr-src-06','https://t.me/punjab_drug_watch/245','Chitta lab busted near Yamunanagar','Underground chitta processing lab busted near Yamunanagar. Raw opium from Rajasthan processed into chitta. 3 arrested including chemistry graduate. Lab equipment worth Rs 50 lakh seized.', md5('hr-ci-18'),'en',NOW()-INTERVAL '16 days',20.0,'hr-cl-02','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@punjab_drug_watch","author_id":"punjab_drug_watch","engagement":{"likes":18,"comments":30,"shares":0,"views":720,"forwards":16},"sentiment":{"compound":-0.65,"label":"negative"},"keywords":["chitta lab","Yamunanagar","opium","Rajasthan","processing"]}'::jsonb,NOW()-INTERVAL '16 days',NOW(),'org_cyber'),
('hr-ci-19','hr-stf-001','hr-src-04','https://amarujala.com/haryana-mothers-anti-drug','Mothers Against Drugs rally in Panchkula','Amar Ujala: Hundreds of mothers march in Panchkula demanding strict action against drug peddlers. Carry photographs of children lost to chitta. Demand NDPS Act be applied without bail provisions.', md5('hr-ci-19'),'en',NOW()-INTERVAL '14 days',72.0,'hr-cl-02','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Amar Ujala","author_id":"hr-src-04","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.3,"label":"negative"},"keywords":["mothers","rally","Panchkula","chitta","NDPS","peddlers"]}'::jsonb,NOW()-INTERVAL '14 days',NOW(),'org_cyber'),
('hr-ci-20','hr-stf-001','hr-src-08','https://t.me/ncr_underground_intel/95','Synthetic drug alternative emerging','New synthetic drug "party powder" emerging as chitta alternative in Haryana colleges. Cheaper at Rs 500/dose. Sold via Instagram DMs. Chemical composition unknown. Two hospitalized in Kurukshetra after use.', md5('hr-ci-20'),'en',NOW()-INTERVAL '11 days',15.0,'hr-cl-02','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@ncr_underground_intel","author_id":"ncr_underground_intel","engagement":{"likes":6,"comments":18,"shares":0,"views":290,"forwards":7},"sentiment":{"compound":-0.7,"label":"negative"},"keywords":["synthetic drug","party powder","colleges","Instagram","Kurukshetra"]}'::jsonb,NOW()-INTERVAL '11 days',NOW(),'org_cyber'),
('hr-ci-21','hr-stf-001','hr-src-05','https://indianexpress.com/haryana-drug-rehab-expansion','Haryana announces 5 new drug rehab centers','Indian Express: Haryana government announces 5 new drug rehabilitation centers in Ambala, Karnal, Panchkula, Hisar, and Rohtak. Rs 100 crore allocated. Each center to have 200-bed capacity. Operational by December.', md5('hr-ci-21'),'en',NOW()-INTERVAL '8 days',78.0,'hr-cl-02','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Indian Express","author_id":"hr-src-05","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.3,"label":"positive"},"keywords":["rehabilitation","centers","Ambala","Karnal","Panchkula","government"]}'::jsonb,NOW()-INTERVAL '8 days',NOW(),'org_cyber'),
('hr-ci-22','hr-stf-001','hr-src-07','https://t.me/haryana_crime_updates/595','Village sarpanch leads anti-drug patrol','Sarpanch of village near Ambala organizes nightly patrols to catch drug peddlers. Community vigilance committees formed in 15 villages. Two peddlers caught and handed to police. Model being replicated.', md5('hr-ci-22'),'en',NOW()-INTERVAL '5 days',25.0,'hr-cl-02','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@haryana_crime_updates","author_id":"haryana_crime_updates","engagement":{"likes":56,"comments":34,"shares":0,"views":1200,"forwards":20},"sentiment":{"compound":0.2,"label":"positive"},"keywords":["sarpanch","anti-drug","patrol","community","Ambala","vigilance"]}'::jsonb,NOW()-INTERVAL '5 days',NOW(),'org_cyber'),

-- ── Cluster 3: STF Operations and Major Arrests (10 items) ──
('hr-ci-23','hr-stf-001','hr-src-10','https://haryanapolice.gov.in/stf-operation-thunder','Operation Thunder: STF arrests 15 drug lords','Haryana Police press release: Operation Thunder conducted across 8 districts simultaneously. 15 drug lords arrested including 3 absconders. Rs 120 crore worth narcotics seized. Inter-state coordination with Punjab, Rajasthan, and Delhi Police.', md5('hr-ci-23'),'en',NOW()-INTERVAL '24 days',90.0,'hr-cl-03','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Haryana Police","author_id":"hr-src-10","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.3,"label":"negative"},"keywords":["Operation Thunder","STF","arrests","drug lords","seizure"]}'::jsonb,NOW()-INTERVAL '24 days',NOW(),'org_cyber'),
('hr-ci-24','hr-stf-001','hr-src-01','https://tribuneindia.com/stf-ambala-kingpin','STF arrests Ambala drug kingpin','Tribune India: STF arrests Ambala-based drug kingpin Sukhwinder alias Sukhi who had been operating for 8 years. Network spread across 3 states. Rs 15 crore cash and 10 kg heroin recovered. Was using Telegram for coordination.', md5('hr-ci-24'),'en',NOW()-INTERVAL '22 days',82.0,'hr-cl-03','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Tribune India","author_id":"hr-src-01","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.4,"label":"negative"},"keywords":["STF","kingpin","Ambala","Sukhwinder","heroin","Telegram"]}'::jsonb,NOW()-INTERVAL '22 days',NOW(),'org_cyber'),
('hr-ci-25','hr-stf-001','hr-src-07','https://t.me/haryana_crime_updates/575','Financial trail reveals hawala network','STF investigation into drug money trail reveals hawala network operating from Panchkula. Money routed through Dubai to Pakistan. 4 hawala operators arrested. Bank accounts worth Rs 8 crore frozen under PMLA.', md5('hr-ci-25'),'en',NOW()-INTERVAL '20 days',25.0,'hr-cl-03','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@haryana_crime_updates","author_id":"haryana_crime_updates","engagement":{"likes":34,"comments":56,"shares":0,"views":1100,"forwards":25},"sentiment":{"compound":-0.55,"label":"negative"},"keywords":["hawala","Panchkula","drug money","Dubai","PMLA","bank accounts"]}'::jsonb,NOW()-INTERVAL '20 days',NOW(),'org_cyber'),
('hr-ci-26','hr-stf-001','hr-src-03','https://hindustantimes.com/chandigarh/stf-panchkula-raid','STF raids Panchkula farmhouse, seizes synthetic drugs','Hindustan Times: STF raids luxury farmhouse in Panchkula sector 20. 8 kg MDMA and 2 kg cocaine seized. Farmhouse owner arrested — retired army officer turned drug supplier. Party drugs being supplied to Chandigarh nightclubs.', md5('hr-ci-26'),'en',NOW()-INTERVAL '17 days',80.0,'hr-cl-03','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Hindustan Times","author_id":"hr-src-03","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.5,"label":"negative"},"keywords":["STF","raid","Panchkula","MDMA","cocaine","farmhouse"]}'::jsonb,NOW()-INTERVAL '17 days',NOW(),'org_cyber'),
('hr-ci-27','hr-stf-001','hr-src-12','https://youtube.com/watch?v=stf_press_conf','STF press conference: Major operation results','Haryana STF IG addresses press conference on Operation Thunder results. Details 3-month intelligence operation. 47 accused identified, 15 arrested, 32 still at large. Appeals for public cooperation. Announces anonymous tip hotline.', md5('hr-ci-27'),'en',NOW()-INTERVAL '15 days',85.0,'hr-cl-03','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Haryana Police Press","author_id":"hr-src-12","engagement":{"likes":120,"comments":45,"shares":30,"views":8500},"sentiment":{"compound":-0.2,"label":"negative"},"keywords":["STF","press conference","Operation Thunder","IG","anonymous tip"]}'::jsonb,NOW()-INTERVAL '15 days',NOW(),'org_cyber'),
('hr-ci-28','hr-stf-001','hr-src-08','https://t.me/ncr_underground_intel/92','Dark web drug market targeting Haryana','Dark web marketplace listing heroin and synthetic drugs with Haryana delivery. Seller uses moniker "PunjabPharma420". Accepts crypto only. Ships via India Post in disguised packages. Active since 3 months.', md5('hr-ci-28'),'en',NOW()-INTERVAL '13 days',15.0,'hr-cl-03','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@ncr_underground_intel","author_id":"ncr_underground_intel","engagement":{"likes":3,"comments":10,"shares":0,"views":220,"forwards":5},"sentiment":{"compound":-0.8,"label":"negative"},"keywords":["dark web","heroin","synthetic drugs","crypto","India Post"]}'::jsonb,NOW()-INTERVAL '13 days',NOW(),'org_cyber'),
('hr-ci-29','hr-stf-001','hr-src-02','https://jagran.com/haryana-stf-women-gang','STF busts all-women drug courier gang','Dainik Jagran: STF busts all-women drug courier gang operating in Ambala-Karnal sector. 6 women arrested, used to carry drugs in modified handbags and undergarments. Gang was operational for 2 years.', md5('hr-ci-29'),'en',NOW()-INTERVAL '10 days',75.0,'hr-cl-03','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Dainik Jagran","author_id":"hr-src-02","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.45,"label":"negative"},"keywords":["STF","women","courier","gang","Ambala","Karnal"]}'::jsonb,NOW()-INTERVAL '10 days',NOW(),'org_cyber'),
('hr-ci-30','hr-stf-001','hr-src-04','https://amarujala.com/haryana-ndps-court','Fast-track NDPS courts announced for Haryana','Amar Ujala: High Court approves 3 fast-track NDPS courts in Ambala, Karnal, and Panchkula. Will expedite drug case trials. Currently 4,500 pending NDPS cases in Haryana. Average case takes 3 years for conviction.', md5('hr-ci-30'),'en',NOW()-INTERVAL '7 days',72.0,'hr-cl-03','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Amar Ujala","author_id":"hr-src-04","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.15,"label":"neutral"},"keywords":["NDPS","courts","fast-track","Ambala","Karnal","Panchkula"]}'::jsonb,NOW()-INTERVAL '7 days',NOW(),'org_cyber'),
('hr-ci-31','hr-stf-001','hr-src-06','https://t.me/punjab_drug_watch/260','STF informant network expanding','STF building informant network in border villages. Offering cash rewards for actionable intelligence. Phone: +91-98765-33333. Anonymity guaranteed. Focus on Ambala, Karnal, Kurukshetra districts.', md5('hr-ci-31'),'en',NOW()-INTERVAL '4 days',20.0,'hr-cl-03','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@punjab_drug_watch","author_id":"punjab_drug_watch","engagement":{"likes":10,"comments":15,"shares":0,"views":450,"forwards":8},"sentiment":{"compound":0.1,"label":"neutral"},"keywords":["STF","informant","intelligence","Ambala","Karnal","Kurukshetra"]}'::jsonb,NOW()-INTERVAL '4 days',NOW(),'org_cyber'),
('hr-ci-32','hr-stf-001','hr-src-05','https://indianexpress.com/haryana-stf-tech','STF adopts AI-driven surveillance','Indian Express: Haryana STF adopts technology-driven approach. Using ANPR cameras at toll plazas, social media monitoring, and AI-driven surveillance for tracking drug networks. Rs 10 crore budget allocated.', md5('hr-ci-32'),'en',NOW()-INTERVAL '2 days',78.0,'hr-cl-03','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Indian Express","author_id":"hr-src-05","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.25,"label":"positive"},"keywords":["STF","AI","surveillance","ANPR","social media","technology"]}'::jsonb,NOW()-INTERVAL '2 days',NOW(),'org_cyber'),

-- ── Cluster 4: Cross-Border Smuggling Networks via Punjab (8 items) ──
('hr-ci-33','hr-stf-001','hr-src-11','https://narcoticsindia.nic.in/afghan-heroin-pipeline','NCB report: Afghan heroin pipeline through India','NCB intelligence report: Afghan heroin enters India via Pakistan-Punjab border. Routed through Amritsar-Jalandhar-Ambala-Delhi pipeline. Haryana is the critical transit zone. Estimated 30 tons annual flow through this corridor.', md5('hr-ci-33'),'en',NOW()-INTERVAL '25 days',92.0,'hr-cl-04','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"NCB India","author_id":"hr-src-11","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.5,"label":"negative"},"keywords":["Afghan heroin","pipeline","Pakistan","Punjab","Amritsar","corridor"]}'::jsonb,NOW()-INTERVAL '25 days',NOW(),'org_cyber'),
('hr-ci-34','hr-stf-001','hr-src-08','https://t.me/ncr_underground_intel/88','Cross-border drone drops increasing','Cross-border drone drops of heroin increasing along Punjab border. 15 drone incidents in last 2 months. Payloads of 5-10 kg each. Drones purchased from China via dark web. GPS coordinates shared via Telegram.', md5('hr-ci-34'),'en',NOW()-INTERVAL '23 days',15.0,'hr-cl-04','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@ncr_underground_intel","author_id":"ncr_underground_intel","engagement":{"likes":7,"comments":12,"shares":0,"views":380,"forwards":9},"sentiment":{"compound":-0.7,"label":"negative"},"keywords":["drone","heroin","Punjab border","China","GPS","Telegram"]}'::jsonb,NOW()-INTERVAL '23 days',NOW(),'org_cyber'),
('hr-ci-35','hr-stf-001','hr-src-01','https://tribuneindia.com/bsf-anti-drone','BSF deploys anti-drone system at Punjab border','Tribune India: BSF deploys anti-drone detection and jamming system along Haryana-Punjab border sector. System can detect drones up to 4 km range. 3 drones neutralized in first week of deployment.', md5('hr-ci-35'),'en',NOW()-INTERVAL '20 days',82.0,'hr-cl-04','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Tribune India","author_id":"hr-src-01","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.1,"label":"neutral"},"keywords":["BSF","anti-drone","Punjab border","detection","jamming"]}'::jsonb,NOW()-INTERVAL '20 days',NOW(),'org_cyber'),
('hr-ci-36','hr-stf-001','hr-src-09','https://t.me/chitta_alert_hrpb/55','Smuggling via agricultural trucks','New MO: drugs hidden in agricultural produce trucks (wheat, sugarcane). Punjab farmers recruited as unwitting carriers. Drugs placed in grain sacks without driver knowledge. Phone contact: +91-98765-11111.', md5('hr-ci-36'),'en',NOW()-INTERVAL '17 days',12.0,'hr-cl-04','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@chitta_alert_hrpb","author_id":"chitta_alert_hrpb","engagement":{"likes":12,"comments":22,"shares":0,"views":510,"forwards":11},"sentiment":{"compound":-0.6,"label":"negative"},"keywords":["smuggling","agricultural","trucks","wheat","farmers","Punjab"]}'::jsonb,NOW()-INTERVAL '17 days',NOW(),'org_cyber'),
('hr-ci-37','hr-stf-001','hr-src-03','https://hindustantimes.com/chandigarh/pak-handler','Pakistan-based handler coordinating Haryana supply','Hindustan Times exclusive: NIA investigation reveals Pakistan-based handler coordinating drug supply to Haryana via Punjab. Uses encrypted communication apps. 3 Indian agents identified, 1 arrested in Ambala.', md5('hr-ci-37'),'en',NOW()-INTERVAL '14 days',80.0,'hr-cl-04','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Hindustan Times","author_id":"hr-src-03","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.65,"label":"negative"},"keywords":["Pakistan","handler","NIA","encrypted","Ambala","supply"]}'::jsonb,NOW()-INTERVAL '14 days',NOW(),'org_cyber'),
('hr-ci-38','hr-stf-001','hr-src-13','http://ahmia.onion/haryana-drug-market','Dark web forum discussing Haryana drug routes','Dark web forum post discussing safest drug transport routes through Haryana. Mentions avoiding Ambala and using Hisar-Rohtak route instead. Users share tips on evading police checkpoints. Post from 2 weeks ago.', md5('hr-ci-38'),'en',NOW()-INTERVAL '11 days',5.0,'hr-cl-04','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Ahmia Onion","author_id":"hr-src-13","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.5,"label":"negative"},"keywords":["dark web","routes","Haryana","Hisar","Rohtak","checkpoints"]}'::jsonb,NOW()-INTERVAL '11 days',NOW(),'org_cyber'),
('hr-ci-39','hr-stf-001','hr-src-07','https://t.me/haryana_crime_updates/590','Crypto used for drug payments','Drug syndicates shifting to cryptocurrency payments. USDT transfers via P2P platforms. No bank trail. STF cyber cell tracking but blockchain analysis capabilities limited. Handle @crypto_maal_786 active on Telegram.', md5('hr-ci-39'),'en',NOW()-INTERVAL '8 days',25.0,'hr-cl-04','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@haryana_crime_updates","author_id":"haryana_crime_updates","engagement":{"likes":20,"comments":35,"shares":0,"views":780,"forwards":16},"sentiment":{"compound":-0.5,"label":"negative"},"keywords":["cryptocurrency","USDT","P2P","blockchain","Telegram","drug payments"]}'::jsonb,NOW()-INTERVAL '8 days',NOW(),'org_cyber'),
('hr-ci-40','hr-stf-001','hr-src-04','https://amarujala.com/haryana-border-fencing','Haryana demands border fencing with Punjab','Amar Ujala: Haryana demands enhanced border fencing and checkpoints along Punjab border specifically for drug control. CM writes to Centre citing 300% increase in drug seizures from Punjab direction.', md5('hr-ci-40'),'en',NOW()-INTERVAL '5 days',72.0,'hr-cl-04','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Amar Ujala","author_id":"hr-src-04","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.3,"label":"negative"},"keywords":["border fencing","Punjab","CM","drug control","checkpoints"]}'::jsonb,NOW()-INTERVAL '5 days',NOW(),'org_cyber'),

-- ── Cluster 5: Youth Anti-Drug Movement and Rehabilitation (8 items) ──
('hr-ci-41','hr-stf-001','hr-src-05','https://indianexpress.com/haryana-youth-anti-drug','Youth-led Drug Free Haryana campaign','Indian Express: College students launch #DrugFreeHaryana campaign on social media. Viral videos showing drug impact on families. 50,000 signatures on petition to CM. Campaign started in Kurukshetra University, spreading statewide.', md5('hr-ci-41'),'en',NOW()-INTERVAL '20 days',78.0,'hr-cl-05','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Indian Express","author_id":"hr-src-05","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.4,"label":"positive"},"keywords":["DrugFreeHaryana","youth","campaign","petition","Kurukshetra"]}'::jsonb,NOW()-INTERVAL '20 days',NOW(),'org_cyber'),
('hr-ci-42','hr-stf-001','hr-src-07','https://t.me/haryana_crime_updates/572','Ex-addicts share recovery stories','Powerful: Former chitta addicts sharing recovery stories on Telegram and YouTube. Documenting their journey from addiction to rehabilitation. One video from Ambala youth has 50K views. Inspiring others to seek help.', md5('hr-ci-42'),'en',NOW()-INTERVAL '18 days',25.0,'hr-cl-05','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@haryana_crime_updates","author_id":"haryana_crime_updates","engagement":{"likes":78,"comments":45,"shares":0,"views":2100,"forwards":30},"sentiment":{"compound":0.5,"label":"positive"},"keywords":["recovery","addicts","stories","rehabilitation","Ambala","YouTube"]}'::jsonb,NOW()-INTERVAL '18 days',NOW(),'org_cyber'),
('hr-ci-43','hr-stf-001','hr-src-02','https://jagran.com/haryana-ngo-rehab','NGOs fill gap in government drug rehab','Dainik Jagran: Private NGOs running 15 drug rehabilitation centers across Haryana, filling gap left by inadequate government facilities. Nasha Mukti Abhiyan organization treating 500 patients monthly.', md5('hr-ci-43'),'en',NOW()-INTERVAL '15 days',75.0,'hr-cl-05','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Dainik Jagran","author_id":"hr-src-02","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.2,"label":"positive"},"keywords":["NGO","rehabilitation","Nasha Mukti","treatment","government gap"]}'::jsonb,NOW()-INTERVAL '15 days',NOW(),'org_cyber'),
('hr-ci-44','hr-stf-001','hr-src-12','https://youtube.com/watch?v=anti_drug_rally','Anti-drug rally in Karnal — 10,000 march','Haryana Police YouTube: Video coverage of massive anti-drug rally in Karnal. 10,000 citizens march. CM addresses crowd, promises zero tolerance. STF IG announces reward scheme for drug tip-offs. Phone: +91-98765-33333.', md5('hr-ci-44'),'en',NOW()-INTERVAL '12 days',85.0,'hr-cl-05','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Haryana Police Press","author_id":"hr-src-12","engagement":{"likes":230,"comments":78,"shares":56,"views":15000},"sentiment":{"compound":0.35,"label":"positive"},"keywords":["anti-drug rally","Karnal","CM","STF","reward","tip-offs"]}'::jsonb,NOW()-INTERVAL '12 days',NOW(),'org_cyber'),
('hr-ci-45','hr-stf-001','hr-src-09','https://t.me/chitta_alert_hrpb/60','Community watch groups in Ambala villages','Community watch groups active in 25 Ambala villages. Night patrols catch 3 peddlers this week. Panchayats passing resolutions banning known drug users from village events. Social pressure working alongside police action.', md5('hr-ci-45'),'en',NOW()-INTERVAL '10 days',12.0,'hr-cl-05','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@chitta_alert_hrpb","author_id":"chitta_alert_hrpb","engagement":{"likes":34,"comments":28,"shares":0,"views":680,"forwards":12},"sentiment":{"compound":0.25,"label":"positive"},"keywords":["community watch","Ambala","panchayat","peddlers","social pressure"]}'::jsonb,NOW()-INTERVAL '10 days',NOW(),'org_cyber'),
('hr-ci-46','hr-stf-001','hr-src-01','https://tribuneindia.com/haryana-school-awareness','Drug awareness program in 500 Haryana schools','Tribune India: Haryana Education Dept launches drug awareness program in 500 schools across Ambala, Karnal, and Panchkula. Police officers give talks. Students take anti-drug pledge. Peer counselor program introduced.', md5('hr-ci-46'),'en',NOW()-INTERVAL '8 days',82.0,'hr-cl-05','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Tribune India","author_id":"hr-src-01","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.5,"label":"positive"},"keywords":["school","awareness","Ambala","Karnal","Panchkula","pledge"]}'::jsonb,NOW()-INTERVAL '8 days',NOW(),'org_cyber'),
('hr-ci-47','hr-stf-001','hr-src-06','https://t.me/punjab_drug_watch/255','Rehabilitation success rate improving','Good news: Haryana drug rehab success rate improving to 45% from 30% last year. New AIIMS-protocol detox program showing results. Key factor: follow-up support after discharge. Family involvement critical.', md5('hr-ci-47'),'en',NOW()-INTERVAL '6 days',20.0,'hr-cl-05','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"@punjab_drug_watch","author_id":"punjab_drug_watch","engagement":{"likes":42,"comments":20,"shares":0,"views":950,"forwards":14},"sentiment":{"compound":0.45,"label":"positive"},"keywords":["rehabilitation","success rate","AIIMS","detox","follow-up"]}'::jsonb,NOW()-INTERVAL '6 days',NOW(),'org_cyber'),
('hr-ci-48','hr-stf-001','hr-src-03','https://hindustantimes.com/chandigarh/sports-anti-drug','Sports as anti-drug tool in Haryana','Hindustan Times: Sports department launches "Khelo, Nasha Nahi" initiative in Ambala and Karnal. Free coaching in wrestling, kabaddi, boxing for at-risk youth. 2000 enrolled in first month. Athletes share anti-drug messages.', md5('hr-ci-48'),'en',NOW()-INTERVAL '3 days',80.0,'hr-cl-05','{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber","author_handle":"Hindustan Times","author_id":"hr-src-03","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.6,"label":"positive"},"keywords":["sports","Khelo Nasha Nahi","wrestling","kabaddi","Ambala","Karnal"]}'::jsonb,NOW()-INTERVAL '3 days',NOW(),'org_cyber')
ON CONFLICT (id) DO NOTHING;

-- ==========================================================================
-- 5. Extracted Entities (NER results)
-- ==========================================================================
INSERT INTO extracted_entities (id, content_item_id, entity_type, entity_text, created_at, labels) VALUES
-- Drug corridor entities
('hr-ent-001','hr-ci-01','ORG','STF Haryana',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-002','hr-ci-01','ORG','NCB',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-003','hr-ci-01','GPE','Ambala',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-004','hr-ci-02','GPE','Karnal',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-005','hr-ci-02','GPE','Rajasthan',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-006','hr-ci-05','GPE','Punjab',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-007','hr-ci-05','GPE','Delhi',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-008','hr-ci-07','ORG','BSF',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-009','hr-ci-07','GPE','Sirsa',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-010','hr-ci-08','GPE','Amritsar',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
-- Chitta epidemic entities
('hr-ent-011','hr-ci-13','GPE','Ambala',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-012','hr-ci-15','GPE','Karnal',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-013','hr-ci-18','GPE','Yamunanagar',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-014','hr-ci-19','GPE','Panchkula',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-015','hr-ci-19','ORG','Mothers Against Drugs',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
-- STF operations entities
('hr-ent-016','hr-ci-23','ORG','Haryana Police',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-017','hr-ci-24','PERSON','Sukhwinder',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-018','hr-ci-25','GPE','Dubai',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-019','hr-ci-26','GPE','Chandigarh',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
-- Cross-border entities
('hr-ent-020','hr-ci-33','GPE','Afghanistan',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-021','hr-ci-33','GPE','Pakistan',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-022','hr-ci-37','ORG','NIA',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
-- Anti-drug movement entities
('hr-ent-023','hr-ci-41','GPE','Kurukshetra',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-024','hr-ci-43','ORG','Nasha Mukti Abhiyan',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-025','hr-ci-44','GPE','Karnal',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
-- Phone numbers as entities
('hr-ent-026','hr-ci-03','PHONE_IN','+91-98765-11111',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-027','hr-ci-09','PHONE_IN','+91-98765-11111',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-028','hr-ci-36','PHONE_IN','+91-98765-11111',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-029','hr-ci-06','PHONE_IN','+91-98765-22222',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-030','hr-ci-11','PHONE_IN','+91-98765-22222',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-031','hr-ci-31','PHONE_IN','+91-98765-33333',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
('hr-ent-032','hr-ci-44','PHONE_IN','+91-98765-33333',NOW(),'{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ==========================================================================
-- 6. Identifier Clusters (Engine C)
-- ==========================================================================
INSERT INTO identifier_clusters (id, topic_id, identifier_type, identifier_value, source_count, content_item_count, first_seen_at, last_seen_at, created_at, updated_at, labels) VALUES
    ('hr-ic-01', 'hr-stf-001', 'PHONE_IN', '9876511111', 3, 3, NOW()-INTERVAL '26 days', NOW()-INTERVAL '6 days', NOW()-INTERVAL '26 days', NOW(), '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
    ('hr-ic-02', 'hr-stf-001', 'PHONE_IN', '9876522222', 2, 2, NOW()-INTERVAL '22 days', NOW()-INTERVAL '12 days', NOW()-INTERVAL '22 days', NOW(), '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
    ('hr-ic-03', 'hr-stf-001', 'PHONE_IN', '9876533333', 2, 2, NOW()-INTERVAL '12 days', NOW()-INTERVAL '4 days', NOW()-INTERVAL '12 days', NOW(), '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
    ('hr-ic-04', 'hr-stf-001', 'TELEGRAM_HANDLE', 'delhimaaldrop', 1, 1, NOW()-INTERVAL '22 days', NOW()-INTERVAL '22 days', NOW()-INTERVAL '22 days', NOW(), '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
    ('hr-ic-05', 'hr-stf-001', 'TELEGRAM_HANDLE', 'ncr_supply_786', 1, 1, NOW()-INTERVAL '22 days', NOW()-INTERVAL '22 days', NOW()-INTERVAL '22 days', NOW(), '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb),
    ('hr-ic-06', 'hr-stf-001', 'TELEGRAM_HANDLE', 'crypto_maal_786', 1, 1, NOW()-INTERVAL '8 days', NOW()-INTERVAL '8 days', NOW()-INTERVAL '8 days', NOW(), '{"classification":"RESTRICTED","domain":"narcotics","owner_org":"cyber"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO identifier_cluster_items (identifier_cluster_id, content_item_id, source_id) VALUES
    ('hr-ic-01', 'hr-ci-03', 'hr-src-06'),
    ('hr-ic-01', 'hr-ci-09', 'hr-src-09'),
    ('hr-ic-01', 'hr-ci-36', 'hr-src-09'),
    ('hr-ic-02', 'hr-ci-06', 'hr-src-08'),
    ('hr-ic-02', 'hr-ci-11', 'hr-src-06'),
    ('hr-ic-03', 'hr-ci-31', 'hr-src-06'),
    ('hr-ic-03', 'hr-ci-44', 'hr-src-12'),
    ('hr-ic-04', 'hr-ci-06', 'hr-src-08'),
    ('hr-ic-05', 'hr-ci-06', 'hr-src-08'),
    ('hr-ic-06', 'hr-ci-39', 'hr-src-07')
ON CONFLICT DO NOTHING;

-- ==========================================================================
-- 7. Signals (3)
-- ==========================================================================
INSERT INTO signals (id, topic_id, cluster_id, signal_type, description, evidence, status, created_at, updated_at, labels) VALUES
    ('hr-sig-01', 'hr-stf-001', 'hr-cl-01', 'multi_source_convergence',
     'Punjab-Haryana drug corridor narrative detected across 4 independent sources (Tribune India, Hindustan Times, @punjab_drug_watch, @haryana_crime_updates)',
     '{"independent_source_count":4,"severity":"HIGH"}'::jsonb,
     'new', NOW()-INTERVAL '22 days', NOW(), '{"classification":"RESTRICTED","domain":"signal","owner_org":"cyber"}'::jsonb),
    ('hr-sig-02', 'hr-stf-001', NULL, 'identifier_convergence',
     'Phone number +91-98765-11111 found across 3 independent sources linked to drug trafficking intelligence',
     '{"independent_source_count":3,"severity":"HIGH","identifier_type":"PHONE_IN","identifier_value":"9876511111"}'::jsonb,
     'new', NOW()-INTERVAL '16 days', NOW(), '{"classification":"RESTRICTED","domain":"signal","owner_org":"cyber"}'::jsonb),
    ('hr-sig-03', 'hr-stf-001', 'hr-cl-03', 'multi_source_convergence',
     'STF operations narrative detected across 4 independent sources spanning official and social media platforms',
     '{"independent_source_count":4,"severity":"MEDIUM"}'::jsonb,
     'new', NOW()-INTERVAL '10 days', NOW(), '{"classification":"RESTRICTED","domain":"signal","owner_org":"cyber"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ==========================================================================
-- 8. Keyword Alert Rules + Triggers
-- ==========================================================================
INSERT INTO keyword_alert_rules (id, topic_id, keywords, match_mode, is_active, notify_websocket, created_by, org_id, created_at, updated_at, labels) VALUES
    ('hr-alert-01', 'hr-stf-001', ARRAY['heroin', 'chitta', 'poppy husk', 'bhukki', 'smack'], 'any', true, true, 'ec-user-cyber', 'org_cyber', NOW()-INTERVAL '25 days', NOW(), '{"classification":"RESTRICTED","domain":"alert","owner_org":"cyber"}'::jsonb),
    ('hr-alert-02', 'hr-stf-001', ARRAY['seizure', 'arrested', 'busted', 'intercepted', 'NDPS'], 'any', true, true, 'ec-user-cyber', 'org_cyber', NOW()-INTERVAL '25 days', NOW(), '{"classification":"RESTRICTED","domain":"alert","owner_org":"cyber"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO keyword_alert_triggers (id, rule_id, content_item_id, matched_keywords, triggered_at, labels) VALUES
    ('hr-trig-01', 'hr-alert-01', 'hr-ci-01', ARRAY['heroin'], NOW()-INTERVAL '28 days', '{"classification":"RESTRICTED","domain":"alert","owner_org":"cyber"}'::jsonb),
    ('hr-trig-02', 'hr-alert-01', 'hr-ci-09', ARRAY['chitta'], NOW()-INTERVAL '16 days', '{"classification":"RESTRICTED","domain":"alert","owner_org":"cyber"}'::jsonb),
    ('hr-trig-03', 'hr-alert-01', 'hr-ci-13', ARRAY['chitta'], NOW()-INTERVAL '26 days', '{"classification":"RESTRICTED","domain":"alert","owner_org":"cyber"}'::jsonb),
    ('hr-trig-04', 'hr-alert-02', 'hr-ci-23', ARRAY['arrested'], NOW()-INTERVAL '24 days', '{"classification":"RESTRICTED","domain":"alert","owner_org":"cyber"}'::jsonb),
    ('hr-trig-05', 'hr-alert-02', 'hr-ci-02', ARRAY['seized'], NOW()-INTERVAL '27 days', '{"classification":"RESTRICTED","domain":"alert","owner_org":"cyber"}'::jsonb),
    ('hr-trig-06', 'hr-alert-02', 'hr-ci-30', ARRAY['NDPS'], NOW()-INTERVAL '7 days', '{"classification":"RESTRICTED","domain":"alert","owner_org":"cyber"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ==========================================================================
-- 9. Forwarding Chains (for network graph)
-- ==========================================================================
-- @ncr_underground_intel forwards FROM @punjab_drug_watch
UPDATE content_items SET forwarded_from_channel_name = 'punjab_drug_watch' WHERE id IN ('hr-ci-06', 'hr-ci-28', 'hr-ci-34');
-- @chitta_alert_hrpb forwards FROM @haryana_crime_updates
UPDATE content_items SET forwarded_from_channel_name = 'haryana_crime_updates' WHERE id IN ('hr-ci-09', 'hr-ci-16', 'hr-ci-36', 'hr-ci-45');
-- @haryana_crime_updates forwards FROM @punjab_drug_watch
UPDATE content_items SET forwarded_from_channel_name = 'punjab_drug_watch' WHERE id IN ('hr-ci-04', 'hr-ci-22', 'hr-ci-25');

-- ==========================================================================
-- Done. Verify counts:
-- ==========================================================================
SELECT 'Topics' AS entity, COUNT(*) FROM topics WHERE id = 'hr-stf-001'
UNION ALL SELECT 'Sources', COUNT(*) FROM sources WHERE id LIKE 'hr-src-%'
UNION ALL SELECT 'Content Items', COUNT(*) FROM content_items WHERE id LIKE 'hr-ci-%'
UNION ALL SELECT 'Clusters', COUNT(*) FROM narrative_clusters WHERE id LIKE 'hr-cl-%'
UNION ALL SELECT 'Entities', COUNT(*) FROM extracted_entities WHERE id LIKE 'hr-ent-%'
UNION ALL SELECT 'ID Clusters', COUNT(*) FROM identifier_clusters WHERE id LIKE 'hr-ic-%'
UNION ALL SELECT 'Signals', COUNT(*) FROM signals WHERE id LIKE 'hr-sig-%'
UNION ALL SELECT 'Alert Rules', COUNT(*) FROM keyword_alert_rules WHERE id LIKE 'hr-alert-%'
UNION ALL SELECT 'Alert Triggers', COUNT(*) FROM keyword_alert_triggers WHERE id LIKE 'hr-trig-%';
