-- ==========================================================================
-- Kerala Cyber Dome Demo — Online Child Protection Intelligence
-- ==========================================================================
-- Scenario: Kerala Police Cyber Dome monitoring online child exploitation
-- networks, predator activity on social platforms, AI-generated synthetic
-- content, financial trails of exploitation material trade, and cross-platform
-- identity correlation for investigation support.
--
-- Context: Kerala Cyber Dome is India's first dedicated police cyber lab.
-- ACPIA (Agentic Child Protection Investigation Assistant) problem statement
-- from HAC'KP 2026 hackathon maps directly to Anveshak's 5 modules + Engine C.
-- This demo showcases all 12 ACPIA focus areas using Anveshak capabilities.
--
-- NOTE: All content is fictional and focuses on investigation workflows,
-- NOT exploitation material. Content describes surveillance of predator
-- networks, financial trail analysis, and takedown operations.
--
-- Org: org_cyber (reusing existing org for demo user)
-- User: demo_cyber@anveshak.local (existing)
--
-- Idempotent: all INSERTs use ON CONFLICT DO NOTHING.
-- Run: docker exec -i anveshak-postgres-1 psql -U anveshak -d anveshak < scripts/seed_kerala_demo.sql
-- ==========================================================================

-- ==========================================================================
-- 1. Topic
-- ==========================================================================
INSERT INTO topics (
    id, name, keywords, signal_threshold, identifier_signal_threshold,
    status, languages, credibility_min,
    labels, created_at, updated_at, org_id
) VALUES (
    'kl-cyd-001',
    'Kerala Cyber Dome — Online Child Protection Intelligence',
    ARRAY['child exploitation', 'CSAM', 'online predator', 'grooming',
          'sextortion', 'deepfake', 'synthetic content', 'POCSO',
          'cyber tipline', 'NCMEC', 'takedown', 'dark web'],
    2, 2, 'active', ARRAY['en', 'ml'], 20.0,
    '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb,
    NOW() - INTERVAL '30 days', NOW(), 'org_cyber'
) ON CONFLICT (id) DO NOTHING;

-- ==========================================================================
-- 2. Sources (14)
-- ==========================================================================
INSERT INTO sources (id, name, url_or_handle, platform, credibility_score, is_active, health_status, labels, created_at, updated_at, org_id) VALUES
    -- ── RSS / Web News Sources ──
    ('kl-src-01', 'The Hindu - Kerala',           'https://www.thehindu.com/news/national/kerala/feeder/default.rss', 'rss', 85.0, true, 'healthy', '{"classification":"OPEN","domain":"child_protection","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('kl-src-02', 'Manorama Online',               'https://www.manoramaonline.com/rss/kerala.xml',     'rss', 80.0, true, 'healthy', '{"classification":"OPEN","domain":"child_protection","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('kl-src-03', 'Mathrubhumi',                   'https://www.mathrubhumi.com/rss/kerala.xml',       'rss', 78.0, true, 'healthy', '{"classification":"OPEN","domain":"child_protection","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('kl-src-04', 'NDTV - Kerala',                 'https://www.ndtv.com/rss/kerala',                  'rss', 82.0, true, 'healthy', '{"classification":"OPEN","domain":"child_protection","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('kl-src-05', 'Indian Express - Kerala',       'https://indianexpress.com/section/cities/kochi/feed/', 'rss', 80.0, true, 'healthy', '{"classification":"OPEN","domain":"child_protection","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),

    -- ── Telegram Sources (monitoring channels) ──
    ('kl-src-06', 'Cyber Crime Alert Kerala',      'cybercrime_alert_kl',        'telegram', 22.0, true, 'healthy', '{"classification":"RESTRICTED","domain":"child_protection","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('kl-src-07', 'Online Safety Watch India',     'online_safety_watch_in',     'telegram', 18.0, true, 'healthy', '{"classification":"RESTRICTED","domain":"child_protection","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('kl-src-08', 'POCSO Tracker Kerala',          'pocso_tracker_kl',           'telegram', 20.0, true, 'healthy', '{"classification":"RESTRICTED","domain":"child_protection","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),

    -- ── Web (official sources) ──
    ('kl-src-09', 'Kerala Police Cyber Dome',      'https://cyberdome.kerala.gov.in',                  'web',  92.0, true, 'healthy', '{"classification":"OPEN","domain":"child_protection","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('kl-src-10', 'NCPCR India',                   'https://ncpcr.gov.in',                             'web',  90.0, true, 'healthy', '{"classification":"OPEN","domain":"child_protection","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),
    ('kl-src-11', 'Cybertipline India (NCMEC)',    'https://www.missingkids.org/gethelpnow/cybertipline', 'web', 95.0, true, 'healthy', '{"classification":"RESTRICTED","domain":"child_protection","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),

    -- ── Social Media ──
    ('kl-src-12', 'Reddit r/Kerala',               'r/Kerala',                   'reddit', 30.0, true, 'healthy', '{"classification":"OPEN","domain":"child_protection","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),

    -- ── YouTube ──
    ('kl-src-13', 'Kerala Police Official',        'keralapolice_official',      'youtube',  88.0, true, 'healthy', '{"classification":"OPEN","domain":"child_protection","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber'),

    -- ── Dark Web ──
    ('kl-src-14', 'Dark Web Forum Monitor',        'http://juhanurmihxlp77nkq76byazcldy2hlmovfu2epvl5ankdibsot4csyd.onion/', 'darkweb', 5.0, true, 'healthy', '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb, NOW()-INTERVAL '30 days', NOW(), 'org_cyber')
ON CONFLICT (id) DO NOTHING;

-- org_sources visibility
INSERT INTO org_sources (org_id, source_id) VALUES
    ('org_cyber','kl-src-01'),('org_cyber','kl-src-02'),('org_cyber','kl-src-03'),
    ('org_cyber','kl-src-04'),('org_cyber','kl-src-05'),('org_cyber','kl-src-06'),
    ('org_cyber','kl-src-07'),('org_cyber','kl-src-08'),('org_cyber','kl-src-09'),
    ('org_cyber','kl-src-10'),('org_cyber','kl-src-11'),('org_cyber','kl-src-12'),
    ('org_cyber','kl-src-13'),('org_cyber','kl-src-14')
ON CONFLICT DO NOTHING;

-- topic_sources
INSERT INTO topic_sources (topic_id, source_id) VALUES
    ('kl-cyd-001','kl-src-01'),('kl-cyd-001','kl-src-02'),('kl-cyd-001','kl-src-03'),
    ('kl-cyd-001','kl-src-04'),('kl-cyd-001','kl-src-05'),('kl-cyd-001','kl-src-06'),
    ('kl-cyd-001','kl-src-07'),('kl-cyd-001','kl-src-08'),('kl-cyd-001','kl-src-09'),
    ('kl-cyd-001','kl-src-10'),('kl-cyd-001','kl-src-11'),('kl-cyd-001','kl-src-12'),
    ('kl-cyd-001','kl-src-13'),('kl-cyd-001','kl-src-14')
ON CONFLICT DO NOTHING;

-- ==========================================================================
-- 3. Narrative Clusters (5)
-- ==========================================================================
INSERT INTO narrative_clusters (id, topic_id, label, item_count, independent_source_count, executive_summary, created_at, updated_at, labels) VALUES
    ('kl-cl-01', 'kl-cyd-001', 'Online Predator Network Detection on Social Platforms', 12, 5,
     'Multiple reports of predator grooming activity on Instagram, Telegram, and gaming platforms targeting minors in Kerala. Coordinated accounts using fake profiles. Pattern: befriend on gaming platform, migrate to private messaging, escalate demands. Cyber Dome tipline reports surging.',
     NOW()-INTERVAL '25 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
    ('kl-cl-02', 'kl-cyd-001', 'AI-Generated Synthetic Content & Deepfake Detection', 10, 4,
     'Rising trend of AI-generated synthetic exploitation material detected via NCMEC tipline reports and dark web monitoring. Stable Diffusion and open-source image generators being misused. Detection signatures identified via metadata analysis and DIRE model scoring.',
     NOW()-INTERVAL '20 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
    ('kl-cl-03', 'kl-cyd-001', 'Financial Trail Analysis — Payment Networks', 10, 4,
     'Financial investigations reveal cryptocurrency and UPI-based payment networks used for trading exploitation material. Hawala-style value transfer between operators. Crypto wallet clustering identifies connected addresses. Bank account freezing under IT Act Section 69.',
     NOW()-INTERVAL '18 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
    ('kl-cl-04', 'kl-cyd-001', 'Cross-Platform Identity Correlation', 8, 3,
     'Engine C identifier intelligence linking same suspect identifiers across platforms — Telegram handle appearing on dark web forums, phone numbers from Instagram DMs matching WhatsApp groups, email addresses in crypto wallet registrations. Cross-referencing with NCMEC CyberTipline reports.',
     NOW()-INTERVAL '12 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
    ('kl-cl-05', 'kl-cyd-001', 'POCSO Operations & Victim Safeguarding', 8, 4,
     'Kerala Police POCSO operations, rescue missions, and victim safeguarding updates. Cyber Dome coordinating with CWC (Child Welfare Committee), NCPCR, and school counselors. Reporting trends from Childline 1098 and cybertipline increasing month-over-month.',
     NOW()-INTERVAL '8 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ==========================================================================
-- 4. Content Items (48 items across 5 clusters, 30 days)
-- ==========================================================================

-- ── Cluster 1: Online Predator Network Detection (12 items) ──
INSERT INTO content_items (id, topic_id, source_id, url, raw_text, clean_text, content_hash, language, captured_at, credibility_score_at_capture, narrative_cluster_id, labels, created_at, updated_at, org_id) VALUES
('kl-ci-01','kl-cyd-001','kl-src-01','https://thehindu.com/news/national/kerala/cyber-dome-predator-ring','Cyber Dome busts online predator ring','Kerala Police Cyber Dome busts interstate online predator ring targeting school children through gaming platforms. 6 suspects arrested across Kerala, Tamil Nadu, and Karnataka. Investigation revealed suspects created fake gaming profiles to befriend minors on Roblox and Free Fire, then migrated conversations to Telegram and Instagram DMs for exploitation. Over 200 potential victims identified. POCSO cases registered in Ernakulam and Thiruvananthapuram.', md5('kl-ci-01'),'en',NOW()-INTERVAL '28 days',85.0,'kl-cl-01','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"The Hindu","author_id":"kl-src-01","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.7,"label":"negative"},"keywords":["predator ring","gaming","Roblox","Telegram","POCSO","Cyber Dome"]}'::jsonb,NOW()-INTERVAL '28 days',NOW(),'org_cyber'),
('kl-ci-02','kl-cyd-001','kl-src-06','https://t.me/cybercrime_alert_kl/101','Instagram grooming pattern alert','ALERT: Emerging pattern — fake Instagram profiles targeting school-age children in Kochi and Thrissur. Profile characteristics: recently created, stock photos, follows only minors, sends DMs within hours. At least 15 reports to Cyber Dome in last week. Report suspicious profiles to cyberdome@keralapolice.gov.in. Phone: +91-471-2721547.', md5('kl-ci-02'),'en',NOW()-INTERVAL '27 days',22.0,'kl-cl-01','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"@cybercrime_alert_kl","author_id":"cybercrime_alert_kl","engagement":{"likes":34,"comments":56,"shares":0,"views":890,"forwards":22},"sentiment":{"compound":-0.8,"label":"negative"},"keywords":["Instagram","grooming","Kochi","Thrissur","fake profiles","minors"]}'::jsonb,NOW()-INTERVAL '27 days',NOW(),'org_cyber'),
('kl-ci-03','kl-cyd-001','kl-src-07','https://t.me/online_safety_watch_in/205','Gaming platform migration pattern','WARNING: Documented predator migration pattern — initial contact on public gaming platforms (BGMI, Free Fire), followed by friend request on Instagram, then shift to Telegram or WhatsApp for private communication. Parents: check children phone for unknown Telegram contacts. Handle spotted: @safe_gamer_mentor (fake safety account).', md5('kl-ci-03'),'en',NOW()-INTERVAL '26 days',18.0,'kl-cl-01','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"@online_safety_watch_in","author_id":"online_safety_watch_in","engagement":{"likes":45,"comments":30,"shares":0,"views":1200,"forwards":35},"sentiment":{"compound":-0.75,"label":"negative"},"keywords":["gaming","migration","BGMI","Free Fire","predator","pattern"]}'::jsonb,NOW()-INTERVAL '26 days',NOW(),'org_cyber'),
('kl-ci-04','kl-cyd-001','kl-src-02','https://manoramaonline.com/news/kerala/kochi-school-sextortion','Sextortion ring targeting Kochi school students','Manorama Online: Kochi City Police arrest 3 persons running sextortion racket targeting school students. Suspects used fake female profiles on Instagram to solicit personal images, then blackmailed victims for money via UPI. 12 victims identified in Ernakulam district. One suspect operated from West Bengal. Phone: +91-94960-11111 used across multiple cases.', md5('kl-ci-04'),'en',NOW()-INTERVAL '24 days',80.0,'kl-cl-01','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Manorama Online","author_id":"kl-src-02","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.85,"label":"negative"},"keywords":["sextortion","Kochi","school","Instagram","UPI","blackmail"]}'::jsonb,NOW()-INTERVAL '24 days',NOW(),'org_cyber'),
('kl-ci-05','kl-cyd-001','kl-src-09','https://cyberdome.kerala.gov.in/advisory-online-grooming','Cyber Dome advisory on online grooming','Kerala Police Cyber Dome issues advisory on online grooming: 340% increase in cybertipline reports related to child exploitation in Q1 2026 vs Q1 2025. Top platforms: Instagram (42%), Telegram (28%), WhatsApp (18%), gaming apps (12%). Parents advised to monitor children online activity. Schools to conduct cyber safety workshops.', md5('kl-ci-05'),'en',NOW()-INTERVAL '22 days',92.0,'kl-cl-01','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Kerala Cyber Dome","author_id":"kl-src-09","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.5,"label":"negative"},"keywords":["advisory","grooming","cybertipline","340% increase","Instagram","Telegram"]}'::jsonb,NOW()-INTERVAL '22 days',NOW(),'org_cyber'),
('kl-ci-06','kl-cyd-001','kl-src-08','https://t.me/pocso_tracker_kl/78','Discord server predator activity','POCSO Tracker: Discord server identified where suspects share tips on contacting minors. Server has 500+ members, Indian operators. Infiltration by Cyber Dome undercover team ongoing. Server admin uses handle @darkmod_admin. Crypto wallet address bc1q_fake_wallet_1 found in payment channel.', md5('kl-ci-06'),'en',NOW()-INTERVAL '20 days',20.0,'kl-cl-01','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"@pocso_tracker_kl","author_id":"pocso_tracker_kl","engagement":{"likes":12,"comments":25,"shares":0,"views":560,"forwards":18},"sentiment":{"compound":-0.9,"label":"negative"},"keywords":["Discord","predator","infiltration","Cyber Dome","crypto wallet"]}'::jsonb,NOW()-INTERVAL '20 days',NOW(),'org_cyber'),
('kl-ci-07','kl-cyd-001','kl-src-03','https://mathrubhumi.com/news/kerala/tvm-cyber-arrest','Thiruvananthapuram cyber arrest — teacher grooming students','Mathrubhumi: Thiruvananthapuram police arrest private tuition teacher for grooming 4 students via WhatsApp. Suspect used separate phone number (+91-94960-22222) for contacting victims. School reported after student confided in counselor. POCSO Section 11 + IT Act Section 67B charges filed.', md5('kl-ci-07'),'en',NOW()-INTERVAL '18 days',78.0,'kl-cl-01','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Mathrubhumi","author_id":"kl-src-03","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.8,"label":"negative"},"keywords":["Thiruvananthapuram","teacher","grooming","WhatsApp","POCSO","IT Act"]}'::jsonb,NOW()-INTERVAL '18 days',NOW(),'org_cyber'),
('kl-ci-08','kl-cyd-001','kl-src-12','https://reddit.com/r/Kerala/comments/fake123','Reddit thread: Parents concerned about online safety','Reddit r/Kerala thread with 200+ comments. Parents sharing experiences of children receiving suspicious friend requests on Instagram. Multiple mentions of same profile pattern — bio includes "gaming mentor" or "free coaching". Users reporting to Cyber Dome via email. Community awareness growing.', md5('kl-ci-08'),'en',NOW()-INTERVAL '16 days',30.0,'kl-cl-01','{"classification":"OPEN","domain":"child_protection","owner_org":"cyber","author_handle":"r/Kerala","author_id":"kl-src-12","engagement":{"likes":234,"comments":208,"shares":0,"views":15000},"sentiment":{"compound":-0.4,"label":"negative"},"keywords":["parents","Instagram","friend requests","gaming mentor","community","reporting"]}'::jsonb,NOW()-INTERVAL '16 days',NOW(),'org_cyber'),
('kl-ci-09','kl-cyd-001','kl-src-04','https://ndtv.com/kerala-news/cyber-dome-operation-shield','Operation Shield: Cyber Dome multi-state crackdown','NDTV: Kerala Cyber Dome launches Operation Shield — coordinated multi-state crackdown on online predator networks. 14 arrests across 5 states. Digital forensics on 23 seized devices ongoing. International coordination with Interpol ICSE database. SP Cyber Crime: This is the largest such operation in Kerala history.', md5('kl-ci-09'),'en',NOW()-INTERVAL '14 days',82.0,'kl-cl-01','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"NDTV","author_id":"kl-src-04","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.3,"label":"negative"},"keywords":["Operation Shield","Cyber Dome","multi-state","Interpol","ICSE","arrests"]}'::jsonb,NOW()-INTERVAL '14 days',NOW(),'org_cyber'),
('kl-ci-10','kl-cyd-001','kl-src-06','https://t.me/cybercrime_alert_kl/115','WhatsApp group distributing exploitation material','CRITICAL: WhatsApp group identified distributing child exploitation material. Group admin phone: +91-94960-11111 (same number linked to Kochi sextortion case). 340 members. Reported to WhatsApp Trust & Safety and NCMEC. Cyber Dome case registered. DO NOT join or share — possession is criminal offense under IT Act 67B.', md5('kl-ci-10'),'en',NOW()-INTERVAL '12 days',22.0,'kl-cl-01','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"@cybercrime_alert_kl","author_id":"cybercrime_alert_kl","engagement":{"likes":8,"comments":15,"shares":0,"views":340,"forwards":10},"sentiment":{"compound":-0.95,"label":"negative"},"keywords":["WhatsApp","exploitation material","NCMEC","IT Act 67B","phone number"]}'::jsonb,NOW()-INTERVAL '12 days',NOW(),'org_cyber'),
('kl-ci-11','kl-cyd-001','kl-src-13','https://youtube.com/watch?v=cyberdome_awareness','Cyber Dome awareness campaign video','Kerala Police Cyber Dome releases awareness video: How predators target children online. 500K views in 2 days. Covers gaming platform grooming, fake profile identification, reporting mechanisms. Malayalam and English versions. Schools asked to screen during cyber safety week.', md5('kl-ci-11'),'en',NOW()-INTERVAL '10 days',88.0,'kl-cl-01','{"classification":"OPEN","domain":"child_protection","owner_org":"cyber","author_handle":"Kerala Police Official","author_id":"kl-src-13","engagement":{"likes":3400,"comments":450,"shares":890,"views":500000},"sentiment":{"compound":0.3,"label":"positive"},"keywords":["awareness","video","grooming","reporting","schools","Malayalam"]}'::jsonb,NOW()-INTERVAL '10 days',NOW(),'org_cyber'),
('kl-ci-12','kl-cyd-001','kl-src-05','https://indianexpress.com/kerala-cyber-dome-ai-detection','Cyber Dome deploys AI for predator detection','Indian Express: Kerala Cyber Dome becomes first state police unit to deploy AI-driven social media monitoring for predator pattern detection. System flags suspicious account behavior patterns — rapid following of minor accounts, specific language patterns in DMs. 45 accounts flagged in first week of deployment.', md5('kl-ci-12'),'en',NOW()-INTERVAL '8 days',80.0,'kl-cl-01','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Indian Express","author_id":"kl-src-05","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.2,"label":"positive"},"keywords":["AI","detection","social media","monitoring","pattern","accounts flagged"]}'::jsonb,NOW()-INTERVAL '8 days',NOW(),'org_cyber'),

-- ── Cluster 2: AI-Generated Synthetic Content & Deepfake Detection (10 items) ──
('kl-ci-13','kl-cyd-001','kl-src-11','https://missingkids.org/cybertipline-report-q1-2026','NCMEC CyberTipline Q1 2026: AI-generated content surge','NCMEC CyberTipline Q1 2026 report: 35% increase in reports flagged as AI-generated or synthetic exploitation content globally. India ranks 3rd in tip volume. Key indicators: metadata signatures of Stable Diffusion, abnormal skin texture patterns, inconsistent lighting. Automated hash matching insufficient — need visual AI detection.', md5('kl-ci-13'),'en',NOW()-INTERVAL '26 days',95.0,'kl-cl-02','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"NCMEC CyberTipline","author_id":"kl-src-11","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.6,"label":"negative"},"keywords":["NCMEC","AI-generated","synthetic","Stable Diffusion","hash matching","detection"]}'::jsonb,NOW()-INTERVAL '26 days',NOW(),'org_cyber'),
('kl-ci-14','kl-cyd-001','kl-src-09','https://cyberdome.kerala.gov.in/deepfake-detection-lab','Cyber Dome establishes deepfake detection lab','Kerala Cyber Dome establishes dedicated deepfake detection laboratory. Using DIRE (Diffusion Reconstruction Error) model for AI-generated image detection. Accuracy: 94% on known synthetic datasets. Processing 200+ images daily from tipline reports. Trained 15 officers in digital forensics evidence handling.', md5('kl-ci-14'),'en',NOW()-INTERVAL '24 days',92.0,'kl-cl-02','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Kerala Cyber Dome","author_id":"kl-src-09","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.2,"label":"positive"},"keywords":["deepfake","DIRE","detection","laboratory","forensics","synthetic"]}'::jsonb,NOW()-INTERVAL '24 days',NOW(),'org_cyber'),
('kl-ci-15','kl-cyd-001','kl-src-07','https://t.me/online_safety_watch_in/220','Telegram channels sharing AI-generated content','WARNING: Telegram channels identified distributing AI-generated synthetic exploitation content. Channels using invite-only access. Content generated using fine-tuned open-source models. Metadata analysis shows EXIF stripped but PNG chunk data reveals generation parameters. Report channels: @safe_child_report.', md5('kl-ci-15'),'en',NOW()-INTERVAL '22 days',18.0,'kl-cl-02','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"@online_safety_watch_in","author_id":"online_safety_watch_in","engagement":{"likes":15,"comments":20,"shares":0,"views":670,"forwards":25},"sentiment":{"compound":-0.85,"label":"negative"},"keywords":["Telegram","AI-generated","synthetic","metadata","EXIF","open-source models"]}'::jsonb,NOW()-INTERVAL '22 days',NOW(),'org_cyber'),
('kl-ci-16','kl-cyd-001','kl-src-01','https://thehindu.com/news/national/kerala/deepfake-sextortion-case','Deepfake used in sextortion case against minor','The Hindu: First case in Kerala where AI-generated deepfake images used to sextort a 16-year-old student. Suspect created fake images using victim school photos scraped from social media. Demanded Rs 50,000 via UPI. Cyber Dome traced IP and arrested suspect in Kozhikode. UPI ID: predator_fake@paytm linked to multiple cases.', md5('kl-ci-16'),'en',NOW()-INTERVAL '20 days',85.0,'kl-cl-02','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"The Hindu","author_id":"kl-src-01","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.9,"label":"negative"},"keywords":["deepfake","sextortion","Kozhikode","UPI","school photos","AI-generated"]}'::jsonb,NOW()-INTERVAL '20 days',NOW(),'org_cyber'),
('kl-ci-17','kl-cyd-001','kl-src-14','http://ahmia.onion/synthetic-content-market','Dark web synthetic content marketplace detected','Dark web marketplace offering AI-generated synthetic exploitation content as a service. Prices in Monero (XMR). Operator claims content is legal because no real children involved — incorrect under Indian law (IT Act 67B covers virtual depictions). Server likely hosted in jurisdiction with weak enforcement. Wallet: 4_fake_xmr_wallet_addr.', md5('kl-ci-17'),'en',NOW()-INTERVAL '18 days',5.0,'kl-cl-02','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Dark Web Monitor","author_id":"kl-src-14","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.9,"label":"negative"},"keywords":["dark web","marketplace","Monero","AI-generated","IT Act 67B","synthetic"]}'::jsonb,NOW()-INTERVAL '18 days',NOW(),'org_cyber'),
('kl-ci-18','kl-cyd-001','kl-src-04','https://ndtv.com/kerala-news/ai-deepfake-arrests','3 arrested for distributing deepfake exploitation material','NDTV: Kerala Police arrest 3 for distributing AI-generated deepfake exploitation material via Telegram. Suspects used Stable Diffusion XL locally. DIRE model analysis confirmed 97% synthetic probability. Seized computers contain 15,000+ generated images. IT Act 67B and POCSO charges filed. Phone: +91-94960-33333.', md5('kl-ci-18'),'en',NOW()-INTERVAL '16 days',82.0,'kl-cl-02','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"NDTV","author_id":"kl-src-04","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.7,"label":"negative"},"keywords":["deepfake","arrests","Stable Diffusion","DIRE","IT Act 67B","POCSO"]}'::jsonb,NOW()-INTERVAL '16 days',NOW(),'org_cyber'),
('kl-ci-19','kl-cyd-001','kl-src-08','https://t.me/pocso_tracker_kl/85','pHash matching identifies redistributed content','Technical update: Perceptual hash (pHash) matching identifies same exploitation content redistributed across 8 different Telegram channels after image modifications (cropping, filters, resolution changes). pHash catches near-duplicates that cryptographic hashes miss. Anveshak vision module processing 500 images/day for hash matching.', md5('kl-ci-19'),'en',NOW()-INTERVAL '14 days',20.0,'kl-cl-02','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"@pocso_tracker_kl","author_id":"pocso_tracker_kl","engagement":{"likes":10,"comments":18,"shares":0,"views":430,"forwards":12},"sentiment":{"compound":-0.4,"label":"negative"},"keywords":["pHash","matching","near-duplicate","Telegram","vision module","modifications"]}'::jsonb,NOW()-INTERVAL '14 days',NOW(),'org_cyber'),
('kl-ci-20','kl-cyd-001','kl-src-03','https://mathrubhumi.com/news/kerala/fake-video-school','AI-generated fake video targeting school student','Mathrubhumi: AI-generated fake video of 14-year-old Kozhikode student circulated on WhatsApp groups. Face-swap technology used with video from adult content site. Parents filed complaint. Cyber Dome DIRE analysis confirms synthetic generation. WhatsApp cooperating with takedown. Counseling provided to victim through District Child Protection Unit.', md5('kl-ci-20'),'en',NOW()-INTERVAL '11 days',78.0,'kl-cl-02','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Mathrubhumi","author_id":"kl-src-03","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.85,"label":"negative"},"keywords":["fake video","face-swap","Kozhikode","WhatsApp","DIRE","counseling"]}'::jsonb,NOW()-INTERVAL '11 days',NOW(),'org_cyber'),
('kl-ci-21','kl-cyd-001','kl-src-10','https://ncpcr.gov.in/advisory-ai-generated-content','NCPCR advisory on AI-generated exploitation content','NCPCR issues national advisory: AI-generated virtual depictions of child exploitation are criminal under IT Act Section 67B and POCSO Act. No real child needed for offense. States directed to build detection capabilities. Kerala Cyber Dome cited as model for other states to follow.', md5('kl-ci-21'),'en',NOW()-INTERVAL '8 days',90.0,'kl-cl-02','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"NCPCR","author_id":"kl-src-10","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.3,"label":"negative"},"keywords":["NCPCR","advisory","AI-generated","IT Act 67B","POCSO","virtual depictions"]}'::jsonb,NOW()-INTERVAL '8 days',NOW(),'org_cyber'),
('kl-ci-22','kl-cyd-001','kl-src-06','https://t.me/cybercrime_alert_kl/120','EXIF metadata stripping detection','Technical advisory: Suspects now strip EXIF metadata from AI-generated content before distribution. However, PNG chunk analysis, JPEG quantization table patterns, and GAN artifact signatures still reveal synthetic origin. Cyber Dome forensics lab trained on these secondary detection methods. CLIP embedding clustering groups similar generated content.', md5('kl-ci-22'),'en',NOW()-INTERVAL '5 days',22.0,'kl-cl-02','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"@cybercrime_alert_kl","author_id":"cybercrime_alert_kl","engagement":{"likes":18,"comments":12,"shares":0,"views":540,"forwards":15},"sentiment":{"compound":-0.3,"label":"negative"},"keywords":["EXIF","metadata","PNG","GAN artifacts","CLIP","forensics"]}'::jsonb,NOW()-INTERVAL '5 days',NOW(),'org_cyber'),

-- ── Cluster 3: Financial Trail Analysis (10 items) ──
('kl-ci-23','kl-cyd-001','kl-src-01','https://thehindu.com/news/national/kerala/upi-network-exploitation','UPI payment network linked to exploitation trade','The Hindu: Kerala Police Cyber Dome traces UPI payment network used for trading exploitation material. 15 UPI IDs identified operating as a payment ring. Amounts small (Rs 200-500) to avoid detection. Total volume estimated at Rs 12 lakh over 6 months. RBI notified. Bank accounts frozen under Section 69 IT Act.', md5('kl-ci-23'),'en',NOW()-INTERVAL '25 days',85.0,'kl-cl-03','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"The Hindu","author_id":"kl-src-01","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.7,"label":"negative"},"keywords":["UPI","payment network","exploitation","RBI","bank accounts","Section 69"]}'::jsonb,NOW()-INTERVAL '25 days',NOW(),'org_cyber'),
('kl-ci-24','kl-cyd-001','kl-src-06','https://t.me/cybercrime_alert_kl/108','Crypto wallet cluster analysis','INTEL: Blockchain analysis reveals cluster of 8 Bitcoin wallets used for exploitation material purchases on dark web. Wallets connected through common mixing service. Total flow: 2.3 BTC (~Rs 1.5 crore). One wallet (bc1q_fake_wallet_1) traced to Indian exchange KYC. Shared with ED for financial investigation.', md5('kl-ci-24'),'en',NOW()-INTERVAL '23 days',22.0,'kl-cl-03','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"@cybercrime_alert_kl","author_id":"cybercrime_alert_kl","engagement":{"likes":5,"comments":10,"shares":0,"views":280,"forwards":8},"sentiment":{"compound":-0.6,"label":"negative"},"keywords":["Bitcoin","blockchain","crypto wallet","KYC","dark web","ED"]}'::jsonb,NOW()-INTERVAL '23 days',NOW(),'org_cyber'),
('kl-ci-25','kl-cyd-001','kl-src-02','https://manoramaonline.com/news/kerala/hawala-exploitation-network','Hawala network funding exploitation operations','Manorama Online: NIA and Kerala Police joint investigation uncovers hawala network channeling funds for exploitation material production and distribution. Money routed through Dubai and Bangladesh. 4 hawala operators arrested in Malappuram. Rs 25 lakh cash seized. Connection to Telegram channel operations confirmed.', md5('kl-ci-25'),'en',NOW()-INTERVAL '20 days',80.0,'kl-cl-03','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Manorama Online","author_id":"kl-src-02","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.65,"label":"negative"},"keywords":["hawala","NIA","Malappuram","Dubai","Bangladesh","Telegram"]}'::jsonb,NOW()-INTERVAL '20 days',NOW(),'org_cyber'),
('kl-ci-26','kl-cyd-001','kl-src-14','http://ahmia.onion/payment-methods-csam','Dark web forum discusses payment methods','Dark web forum thread discussing payment methods for exploitation material: Monero preferred (privacy coin), Bitcoin accepted with mixing, UPI via mule accounts (Indian market only). Forum admin warns against direct bank transfers. Thread has 150+ replies with operational details. Handle: @darkmod_admin (same as Discord server admin).', md5('kl-ci-26'),'en',NOW()-INTERVAL '18 days',5.0,'kl-cl-03','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Dark Web Monitor","author_id":"kl-src-14","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.9,"label":"negative"},"keywords":["Monero","Bitcoin","UPI","mule accounts","payment","dark web"]}'::jsonb,NOW()-INTERVAL '18 days',NOW(),'org_cyber'),
('kl-ci-27','kl-cyd-001','kl-src-07','https://t.me/online_safety_watch_in/230','UPI mule account pattern identified','PATTERN: Exploitation payment mule accounts use specific pattern — newly created UPI IDs, small amounts (Rs 99-499, below bank monitoring threshold), burst transfers followed by withdrawal, account abandoned within 2 weeks. UPI ID pattern: random_name_digits@paytm. Phone: +91-94960-44444 linked to 3 mule accounts.', md5('kl-ci-27'),'en',NOW()-INTERVAL '15 days',18.0,'kl-cl-03','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"@online_safety_watch_in","author_id":"online_safety_watch_in","engagement":{"likes":8,"comments":15,"shares":0,"views":380,"forwards":10},"sentiment":{"compound":-0.7,"label":"negative"},"keywords":["UPI","mule account","pattern","threshold","burst transfers"]}'::jsonb,NOW()-INTERVAL '15 days',NOW(),'org_cyber'),
('kl-ci-28','kl-cyd-001','kl-src-04','https://ndtv.com/kerala-news/ed-freezes-accounts','ED freezes 23 bank accounts linked to exploitation trade','NDTV: Enforcement Directorate freezes 23 bank accounts across Kerala, Tamil Nadu, and Karnataka linked to child exploitation material trade. Total frozen amount: Rs 45 lakh. Investigation triggered by Cyber Dome referral. PMLA provisions applied. Coordination with RBI and NPCI for UPI transaction forensics.', md5('kl-ci-28'),'en',NOW()-INTERVAL '13 days',82.0,'kl-cl-03','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"NDTV","author_id":"kl-src-04","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.4,"label":"negative"},"keywords":["ED","bank accounts","frozen","PMLA","RBI","NPCI","UPI forensics"]}'::jsonb,NOW()-INTERVAL '13 days',NOW(),'org_cyber'),
('kl-ci-29','kl-cyd-001','kl-src-08','https://t.me/pocso_tracker_kl/90','Crypto-to-UPI conversion service','INTEL: Suspect operating crypto-to-UPI conversion service for exploitation material buyers. Accepts Bitcoin/Monero, converts to INR, transfers via UPI to seller accounts. Commission: 15%. Handle: @crypto_convert_in. Operates on Telegram with referral-only access. Phone: +91-94960-44444.', md5('kl-ci-29'),'en',NOW()-INTERVAL '10 days',20.0,'kl-cl-03','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"@pocso_tracker_kl","author_id":"pocso_tracker_kl","engagement":{"likes":6,"comments":12,"shares":0,"views":310,"forwards":8},"sentiment":{"compound":-0.75,"label":"negative"},"keywords":["crypto","UPI","conversion","Bitcoin","Monero","Telegram"]}'::jsonb,NOW()-INTERVAL '10 days',NOW(),'org_cyber'),
('kl-ci-30','kl-cyd-001','kl-src-05','https://indianexpress.com/kerala-crypto-tracking','Kerala Police builds crypto tracking capability','Indian Express: Kerala Police Cyber Dome builds in-house cryptocurrency tracking capability. Partnership with blockchain analytics firms. Can now trace Bitcoin, Ethereum, and partial Monero transactions. First successful conviction using crypto evidence in POCSO case. Training 20 officers in blockchain forensics.', md5('kl-ci-30'),'en',NOW()-INTERVAL '7 days',80.0,'kl-cl-03','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Indian Express","author_id":"kl-src-05","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.3,"label":"positive"},"keywords":["cryptocurrency","tracking","blockchain","forensics","conviction","training"]}'::jsonb,NOW()-INTERVAL '7 days',NOW(),'org_cyber'),
('kl-ci-31','kl-cyd-001','kl-src-03','https://mathrubhumi.com/news/kerala/gaming-currency-laundering','Gaming currency used for exploitation payments','Mathrubhumi investigation: Suspects using in-game virtual currency (Roblox Robux, Free Fire diamonds) as alternative payment for exploitation material. Converts real money to game currency, transfers to suspect account, suspect cashes out via third-party sites. Difficult to trace. 5 such transactions identified by Cyber Dome.', md5('kl-ci-31'),'en',NOW()-INTERVAL '4 days',78.0,'kl-cl-03','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Mathrubhumi","author_id":"kl-src-03","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.5,"label":"negative"},"keywords":["gaming currency","Roblox","Robux","Free Fire","laundering","virtual currency"]}'::jsonb,NOW()-INTERVAL '4 days',NOW(),'org_cyber'),
('kl-ci-32','kl-cyd-001','kl-src-09','https://cyberdome.kerala.gov.in/financial-intelligence-unit','Cyber Dome financial intelligence unit established','Kerala Police Cyber Dome establishes dedicated financial intelligence unit for tracking exploitation-related money flows. Integrates with FIU-IND, NPCI, and cryptocurrency exchanges. Automated suspicious transaction pattern detection. Unit has frozen Rs 1.2 crore across 45 accounts in first quarter of operation.', md5('kl-ci-32'),'en',NOW()-INTERVAL '2 days',92.0,'kl-cl-03','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Kerala Cyber Dome","author_id":"kl-src-09","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.1,"label":"neutral"},"keywords":["financial intelligence","FIU-IND","NPCI","cryptocurrency","pattern detection","frozen accounts"]}'::jsonb,NOW()-INTERVAL '2 days',NOW(),'org_cyber'),

-- ── Cluster 4: Cross-Platform Identity Correlation (8 items) ──
('kl-ci-33','kl-cyd-001','kl-src-09','https://cyberdome.kerala.gov.in/engine-c-identity-correlation','Cross-platform identity correlation breakthrough','Kerala Cyber Dome cross-platform identity correlation: Same suspect identified across 4 platforms using Engine C identifier intelligence. Telegram handle @darkmod_admin → Discord server admin → dark web forum poster → crypto wallet owner. Phone number +91-94960-11111 appears on Instagram, WhatsApp, and Telegram. Single suspect behind 3 separate reported incidents.', md5('kl-ci-33'),'en',NOW()-INTERVAL '22 days',92.0,'kl-cl-04','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Kerala Cyber Dome","author_id":"kl-src-09","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.3,"label":"negative"},"keywords":["cross-platform","identity","Engine C","Telegram","Discord","dark web"]}'::jsonb,NOW()-INTERVAL '22 days',NOW(),'org_cyber'),
('kl-ci-34','kl-cyd-001','kl-src-06','https://t.me/cybercrime_alert_kl/112','Identifier cluster reveals network','BREAKTHROUGH: Identifier clustering reveals network of 5 connected suspects. Phone +91-94960-11111 found in 4 content items across 3 platforms. Same email (fake_email_suspect@proton.me) registered on dark web forum and crypto exchange. Forwarding chain analysis shows information flow between Telegram channels.', md5('kl-ci-34'),'en',NOW()-INTERVAL '19 days',22.0,'kl-cl-04','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"@cybercrime_alert_kl","author_id":"cybercrime_alert_kl","engagement":{"likes":10,"comments":18,"shares":0,"views":420,"forwards":12},"sentiment":{"compound":-0.5,"label":"negative"},"keywords":["identifier","clustering","network","phone","email","forwarding chain"]}'::jsonb,NOW()-INTERVAL '19 days',NOW(),'org_cyber'),
('kl-ci-35','kl-cyd-001','kl-src-02','https://manoramaonline.com/news/kerala/suspect-multi-platform','Suspect arrested after multi-platform correlation','Manorama Online: Kozhikode man arrested after Cyber Dome multi-platform correlation linked his Telegram handle, Instagram account, and WhatsApp number to exploitation material distribution. Engine C identifier intelligence correlated handle @safe_gamer_mentor across 3 platforms. Device forensics revealed 8,000+ images. POCSO + IT Act charges.', md5('kl-ci-35'),'en',NOW()-INTERVAL '16 days',80.0,'kl-cl-04','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Manorama Online","author_id":"kl-src-02","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.6,"label":"negative"},"keywords":["multi-platform","correlation","Kozhikode","Engine C","device forensics","POCSO"]}'::jsonb,NOW()-INTERVAL '16 days',NOW(),'org_cyber'),
('kl-ci-36','kl-cyd-001','kl-src-07','https://t.me/online_safety_watch_in/235','Email address links dark web to real identity','INTEL: Email address fake_email_suspect@proton.me found on dark web exploitation forum also used for Flipkart and Swiggy accounts. Delivery addresses reveal real-world identity. Shared with Cyber Dome for physical surveillance. Cross-referencing with phone +91-94960-22222.', md5('kl-ci-36'),'en',NOW()-INTERVAL '13 days',18.0,'kl-cl-04','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"@online_safety_watch_in","author_id":"online_safety_watch_in","engagement":{"likes":7,"comments":12,"shares":0,"views":310,"forwards":9},"sentiment":{"compound":-0.5,"label":"negative"},"keywords":["email","dark web","identity","Flipkart","Swiggy","surveillance"]}'::jsonb,NOW()-INTERVAL '13 days',NOW(),'org_cyber'),
('kl-ci-37','kl-cyd-001','kl-src-01','https://thehindu.com/news/national/kerala/interpol-coordination','Kerala-Interpol coordination on cross-border suspects','The Hindu: Kerala Cyber Dome coordinates with Interpol ICSE (International Child Sexual Exploitation) database. 12 hash matches found between Kerala tipline submissions and existing Interpol records. 3 suspects identified as part of international network. Red corner notice requested for 1 suspect who fled to UAE.', md5('kl-ci-37'),'en',NOW()-INTERVAL '10 days',85.0,'kl-cl-04','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"The Hindu","author_id":"kl-src-01","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.4,"label":"negative"},"keywords":["Interpol","ICSE","hash matching","Red corner","UAE","international"]}'::jsonb,NOW()-INTERVAL '10 days',NOW(),'org_cyber'),
('kl-ci-38','kl-cyd-001','kl-src-08','https://t.me/pocso_tracker_kl/92','Telegram forwarding chain maps distribution network','Telegram forwarding chain analysis maps distribution network: Channel A (@darkmod_admin) → Channel B → Channel C. Messages forwarded with consistent 2-3 hour delay suggesting automated bot redistribution. Bot handle: @auto_fwd_bot_xyz. Source channel has 500+ subscribers. Downstream channels smaller but growing.', md5('kl-ci-38'),'en',NOW()-INTERVAL '7 days',20.0,'kl-cl-04','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"@pocso_tracker_kl","author_id":"pocso_tracker_kl","engagement":{"likes":5,"comments":10,"shares":0,"views":250,"forwards":7},"sentiment":{"compound":-0.6,"label":"negative"},"keywords":["forwarding chain","Telegram","distribution","bot","automated","subscribers"]}'::jsonb,NOW()-INTERVAL '7 days',NOW(),'org_cyber'),
('kl-ci-39','kl-cyd-001','kl-src-04','https://ndtv.com/kerala-news/device-forensics-network','Device forensics reveals 15-person network','NDTV: Digital forensics on devices seized during Operation Shield reveals 15-person network across 4 states. Contact lists, chat histories, and shared media analyzed using Anveshak platform. Network topology mapped — 2 kingpins, 5 distributors, 8 consumers. Identifier correlation critical for mapping connections.', md5('kl-ci-39'),'en',NOW()-INTERVAL '4 days',82.0,'kl-cl-04','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"NDTV","author_id":"kl-src-04","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.5,"label":"negative"},"keywords":["device forensics","Operation Shield","network","topology","kingpins","identifier correlation"]}'::jsonb,NOW()-INTERVAL '4 days',NOW(),'org_cyber'),
('kl-ci-40','kl-cyd-001','kl-src-05','https://indianexpress.com/kerala-entity-graph','Entity graph connects 50 suspects across Kerala','Indian Express: Cyber Dome entity relationship graph connects 50 suspects across Kerala in exploitation investigation. Graph built from identifier intelligence — shared phone numbers, common Telegram channels, overlapping crypto wallets. Visualization helps investigators prioritize targets. 8 high-connectivity suspects identified for immediate action.', md5('kl-ci-40'),'en',NOW()-INTERVAL '2 days',80.0,'kl-cl-04','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Indian Express","author_id":"kl-src-05","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.3,"label":"negative"},"keywords":["entity graph","suspects","identifier intelligence","phone numbers","Telegram","crypto wallets"]}'::jsonb,NOW()-INTERVAL '2 days',NOW(),'org_cyber'),

-- ── Cluster 5: POCSO Operations & Victim Safeguarding (8 items) ──
('kl-ci-41','kl-cyd-001','kl-src-10','https://ncpcr.gov.in/pocso-statistics-kerala-q1','NCPCR POCSO statistics Kerala Q1 2026','NCPCR statistics: Kerala registered 342 POCSO cases in Q1 2026, 28% involving online exploitation (up from 15% in Q1 2025). Conviction rate: 42%. Average case duration: 18 months. Cyber Dome evidence quality cited as factor in higher conviction rates for online cases vs traditional cases.', md5('kl-ci-41'),'en',NOW()-INTERVAL '20 days',90.0,'kl-cl-05','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"NCPCR","author_id":"kl-src-10","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.3,"label":"negative"},"keywords":["NCPCR","POCSO","statistics","conviction rate","online exploitation","evidence"]}'::jsonb,NOW()-INTERVAL '20 days',NOW(),'org_cyber'),
('kl-ci-42','kl-cyd-001','kl-src-02','https://manoramaonline.com/news/kerala/cwc-rescue-operation','CWC rescue operation saves 8 children','Manorama Online: Child Welfare Committee Ernakulam conducts rescue operation based on Cyber Dome intelligence. 8 children rescued from exploitation situation in Kochi. Investigation started from cybertipline report, Anveshak platform correlated with 3 prior reports from same location. Accused arrested under POCSO.', md5('kl-ci-42'),'en',NOW()-INTERVAL '18 days',80.0,'kl-cl-05','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Manorama Online","author_id":"kl-src-02","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":-0.4,"label":"negative"},"keywords":["CWC","rescue","Ernakulam","Kochi","cybertipline","POCSO"]}'::jsonb,NOW()-INTERVAL '18 days',NOW(),'org_cyber'),
('kl-ci-43','kl-cyd-001','kl-src-13','https://youtube.com/watch?v=safe_internet_kl','Kerala Police safe internet campaign for children','Kerala Police YouTube: Safe Internet campaign targeting children. Interactive video explaining online safety — what to share, what not to share, how to report. 1 million views. Available in Malayalam, English, Tamil. Schools mandated to screen. Childline 1098 and cybertipline reporting mechanisms explained.', md5('kl-ci-43'),'en',NOW()-INTERVAL '15 days',88.0,'kl-cl-05','{"classification":"OPEN","domain":"child_protection","owner_org":"cyber","author_handle":"Kerala Police Official","author_id":"kl-src-13","engagement":{"likes":5600,"comments":890,"shares":2100,"views":1000000},"sentiment":{"compound":0.6,"label":"positive"},"keywords":["safe internet","campaign","children","Malayalam","Childline","reporting"]}'::jsonb,NOW()-INTERVAL '15 days',NOW(),'org_cyber'),
('kl-ci-44','kl-cyd-001','kl-src-03','https://mathrubhumi.com/news/kerala/school-counselor-training','2000 school counselors trained in cyber safety','Mathrubhumi: Kerala Education Department trains 2000 school counselors in identifying signs of online exploitation. Training conducted by Cyber Dome officers. Counselors equipped with reporting protocols. Red flag indicators: behavioral changes, secretive phone use, unexplained gifts or money. Hotline: +91-94960-55555.', md5('kl-ci-44'),'en',NOW()-INTERVAL '12 days',78.0,'kl-cl-05','{"classification":"OPEN","domain":"child_protection","owner_org":"cyber","author_handle":"Mathrubhumi","author_id":"kl-src-03","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.4,"label":"positive"},"keywords":["school counselors","training","Cyber Dome","red flags","hotline","reporting"]}'::jsonb,NOW()-INTERVAL '12 days',NOW(),'org_cyber'),
('kl-ci-45','kl-cyd-001','kl-src-07','https://t.me/online_safety_watch_in/240','Victim support network established','Kerala establishes multi-agency victim support network: Childline 1098 → Police SHO → CWC → Cyber Dome forensics → DCPU counseling → legal aid. Response time target: 2 hours from report to CWC notification. Phone: +91-94960-55555 for direct Cyber Dome reporting.', md5('kl-ci-45'),'en',NOW()-INTERVAL '10 days',18.0,'kl-cl-05','{"classification":"OPEN","domain":"child_protection","owner_org":"cyber","author_handle":"@online_safety_watch_in","author_id":"online_safety_watch_in","engagement":{"likes":56,"comments":30,"shares":0,"views":1100,"forwards":28},"sentiment":{"compound":0.3,"label":"positive"},"keywords":["victim support","Childline","CWC","DCPU","counseling","reporting"]}'::jsonb,NOW()-INTERVAL '10 days',NOW(),'org_cyber'),
('kl-ci-46','kl-cyd-001','kl-src-01','https://thehindu.com/news/national/kerala/pocso-court-verdict','Kerala POCSO court delivers landmark verdict','The Hindu: Kerala POCSO special court delivers landmark verdict — 20-year sentence for online exploitation case. Digital evidence from Cyber Dome forensics lab accepted as primary evidence. Court commends quality of hash-matching evidence and cross-platform correlation report. Sets precedent for future online exploitation cases.', md5('kl-ci-46'),'en',NOW()-INTERVAL '8 days',85.0,'kl-cl-05','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"The Hindu","author_id":"kl-src-01","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.2,"label":"positive"},"keywords":["POCSO court","verdict","sentence","digital evidence","hash matching","precedent"]}'::jsonb,NOW()-INTERVAL '8 days',NOW(),'org_cyber'),
('kl-ci-47','kl-cyd-001','kl-src-09','https://cyberdome.kerala.gov.in/quarterly-report-q1','Cyber Dome Q1 2026 child protection quarterly report','Kerala Cyber Dome Q1 2026 quarterly report: 1,247 cybertipline reports processed (340% YoY increase). 42 arrests. 23 children rescued. Rs 1.2 crore frozen. 3 international referrals to Interpol. AI detection capabilities: 200+ images/day processed. Platform cooperation: WhatsApp (response time 4h), Instagram (24h), Telegram (48h).', md5('kl-ci-47'),'en',NOW()-INTERVAL '5 days',92.0,'kl-cl-05','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"Kerala Cyber Dome","author_id":"kl-src-09","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.1,"label":"neutral"},"keywords":["quarterly report","cybertipline","arrests","rescued","frozen","platform cooperation"]}'::jsonb,NOW()-INTERVAL '5 days',NOW(),'org_cyber'),
('kl-ci-48','kl-cyd-001','kl-src-04','https://ndtv.com/kerala-news/cyber-dome-model','Kerala Cyber Dome becomes national model for child protection','NDTV: Central government recognizes Kerala Cyber Dome as national model for online child protection. MHA recommends other states adopt similar AI-driven investigation support platforms. Special mention of cross-platform identifier correlation and deepfake detection capabilities. Budget allocation of Rs 50 crore for nationwide replication.', md5('kl-ci-48'),'en',NOW()-INTERVAL '2 days',82.0,'kl-cl-05','{"classification":"SECRET","domain":"child_protection","owner_org":"cyber","author_handle":"NDTV","author_id":"kl-src-04","engagement":{"likes":0,"comments":0,"shares":0,"views":0},"sentiment":{"compound":0.5,"label":"positive"},"keywords":["national model","MHA","AI-driven","identifier correlation","deepfake","replication"]}'::jsonb,NOW()-INTERVAL '2 days',NOW(),'org_cyber')
ON CONFLICT (id) DO NOTHING;

-- ==========================================================================
-- 5. Extracted Entities (NER results)
-- ==========================================================================
INSERT INTO extracted_entities (id, content_item_id, entity_type, entity_text, created_at, labels) VALUES
-- Predator network entities
('kl-ent-001','kl-ci-01','ORG','Kerala Police Cyber Dome',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-002','kl-ci-01','GPE','Ernakulam',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-003','kl-ci-01','GPE','Thiruvananthapuram',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-004','kl-ci-01','GPE','Tamil Nadu',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-005','kl-ci-01','GPE','Karnataka',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-006','kl-ci-04','GPE','Kochi',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-007','kl-ci-04','GPE','West Bengal',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-008','kl-ci-07','GPE','Kozhikode',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-009','kl-ci-09','ORG','Interpol',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-010','kl-ci-09','ORG','ICSE Database',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
-- Deepfake/synthetic entities
('kl-ent-011','kl-ci-13','ORG','NCMEC',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-012','kl-ci-14','ORG','DIRE Model',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-013','kl-ci-16','GPE','Kozhikode',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-014','kl-ci-21','ORG','NCPCR',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
-- Financial trail entities
('kl-ent-015','kl-ci-23','ORG','RBI',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-016','kl-ci-25','ORG','NIA',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-017','kl-ci-25','GPE','Malappuram',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-018','kl-ci-25','GPE','Dubai',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-019','kl-ci-28','ORG','Enforcement Directorate',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-020','kl-ci-32','ORG','FIU-IND',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-021','kl-ci-32','ORG','NPCI',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
-- Cross-platform identity entities
('kl-ent-022','kl-ci-37','ORG','Interpol',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-023','kl-ci-37','GPE','UAE',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
-- POCSO/safeguarding entities
('kl-ent-024','kl-ci-41','ORG','NCPCR',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-025','kl-ci-42','ORG','CWC Ernakulam',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-026','kl-ci-42','GPE','Kochi',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-027','kl-ci-46','ORG','POCSO Special Court',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-028','kl-ci-48','ORG','MHA',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
-- Phone entities
('kl-ent-029','kl-ci-02','PHONE_IN','+91-471-2721547',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-030','kl-ci-04','PHONE_IN','+91-94960-11111',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-031','kl-ci-07','PHONE_IN','+91-94960-22222',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-032','kl-ci-18','PHONE_IN','+91-94960-33333',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-033','kl-ci-27','PHONE_IN','+91-94960-44444',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
('kl-ent-034','kl-ci-44','PHONE_IN','+91-94960-55555',NOW(),'{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ==========================================================================
-- 6. Identifier Clusters (Engine C)
-- ==========================================================================
INSERT INTO identifier_clusters (id, topic_id, identifier_type, identifier_value, source_count, content_item_count, first_seen_at, last_seen_at, created_at, updated_at, labels) VALUES
    ('kl-ic-01', 'kl-cyd-001', 'PHONE_IN', '9496011111', 3, 3, NOW()-INTERVAL '27 days', NOW()-INTERVAL '12 days', NOW()-INTERVAL '27 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
    ('kl-ic-02', 'kl-cyd-001', 'PHONE_IN', '9496022222', 2, 2, NOW()-INTERVAL '18 days', NOW()-INTERVAL '13 days', NOW()-INTERVAL '18 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
    ('kl-ic-03', 'kl-cyd-001', 'PHONE_IN', '9496033333', 1, 1, NOW()-INTERVAL '16 days', NOW()-INTERVAL '16 days', NOW()-INTERVAL '16 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
    ('kl-ic-04', 'kl-cyd-001', 'PHONE_IN', '9496044444', 2, 2, NOW()-INTERVAL '15 days', NOW()-INTERVAL '10 days', NOW()-INTERVAL '15 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
    ('kl-ic-05', 'kl-cyd-001', 'TELEGRAM_HANDLE', 'darkmod_admin', 3, 3, NOW()-INTERVAL '20 days', NOW()-INTERVAL '7 days', NOW()-INTERVAL '20 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
    ('kl-ic-06', 'kl-cyd-001', 'TELEGRAM_HANDLE', 'safe_gamer_mentor', 2, 2, NOW()-INTERVAL '26 days', NOW()-INTERVAL '16 days', NOW()-INTERVAL '26 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
    ('kl-ic-07', 'kl-cyd-001', 'TELEGRAM_HANDLE', 'crypto_convert_in', 1, 1, NOW()-INTERVAL '10 days', NOW()-INTERVAL '10 days', NOW()-INTERVAL '10 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
    ('kl-ic-08', 'kl-cyd-001', 'EMAIL', 'fake_email_suspect@proton.me', 2, 2, NOW()-INTERVAL '19 days', NOW()-INTERVAL '13 days', NOW()-INTERVAL '19 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
    ('kl-ic-09', 'kl-cyd-001', 'CRYPTO_WALLET', 'bc1q_fake_wallet_1', 2, 2, NOW()-INTERVAL '23 days', NOW()-INTERVAL '20 days', NOW()-INTERVAL '23 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb),
    ('kl-ic-10', 'kl-cyd-001', 'UPI_ID', 'predator_fake@paytm', 1, 1, NOW()-INTERVAL '20 days', NOW()-INTERVAL '20 days', NOW()-INTERVAL '20 days', NOW(), '{"classification":"SECRET","domain":"child_protection","owner_org":"cyber"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO identifier_cluster_items (identifier_cluster_id, content_item_id, source_id) VALUES
    ('kl-ic-01', 'kl-ci-02', 'kl-src-06'),
    ('kl-ic-01', 'kl-ci-04', 'kl-src-02'),
    ('kl-ic-01', 'kl-ci-10', 'kl-src-06'),
    ('kl-ic-02', 'kl-ci-07', 'kl-src-03'),
    ('kl-ic-02', 'kl-ci-36', 'kl-src-07'),
    ('kl-ic-03', 'kl-ci-18', 'kl-src-04'),
    ('kl-ic-04', 'kl-ci-27', 'kl-src-07'),
    ('kl-ic-04', 'kl-ci-29', 'kl-src-08'),
    ('kl-ic-05', 'kl-ci-06', 'kl-src-08'),
    ('kl-ic-05', 'kl-ci-26', 'kl-src-14'),
    ('kl-ic-05', 'kl-ci-38', 'kl-src-08'),
    ('kl-ic-06', 'kl-ci-03', 'kl-src-07'),
    ('kl-ic-06', 'kl-ci-35', 'kl-src-02'),
    ('kl-ic-07', 'kl-ci-29', 'kl-src-08'),
    ('kl-ic-08', 'kl-ci-34', 'kl-src-06'),
    ('kl-ic-08', 'kl-ci-36', 'kl-src-07'),
    ('kl-ic-09', 'kl-ci-06', 'kl-src-08'),
    ('kl-ic-09', 'kl-ci-24', 'kl-src-06'),
    ('kl-ic-10', 'kl-ci-16', 'kl-src-01')
ON CONFLICT DO NOTHING;

-- ==========================================================================
-- 7. Signals (4)
-- ==========================================================================
INSERT INTO signals (id, topic_id, cluster_id, signal_type, description, evidence, status, created_at, updated_at, labels) VALUES
    ('kl-sig-01', 'kl-cyd-001', 'kl-cl-01', 'multi_source_convergence',
     'Online predator network narrative detected across 5 independent sources (The Hindu, Manorama, NDTV, @cybercrime_alert_kl, @online_safety_watch_in)',
     '{"independent_source_count":5,"severity":"CRITICAL"}'::jsonb,
     'new', NOW()-INTERVAL '22 days', NOW(), '{"classification":"SECRET","domain":"signal","owner_org":"cyber"}'::jsonb),
    ('kl-sig-02', 'kl-cyd-001', NULL, 'identifier_convergence',
     'Phone number +91-94960-11111 found across 3 independent sources linked to sextortion and exploitation material distribution',
     '{"independent_source_count":3,"severity":"CRITICAL","identifier_type":"PHONE_IN","identifier_value":"9496011111"}'::jsonb,
     'new', NOW()-INTERVAL '16 days', NOW(), '{"classification":"SECRET","domain":"signal","owner_org":"cyber"}'::jsonb),
    ('kl-sig-03', 'kl-cyd-001', NULL, 'identifier_convergence',
     'Telegram handle @darkmod_admin found across 3 independent sources — Discord server, dark web forum, and Telegram forwarding chain',
     '{"independent_source_count":3,"severity":"HIGH","identifier_type":"TELEGRAM_HANDLE","identifier_value":"darkmod_admin"}'::jsonb,
     'new', NOW()-INTERVAL '10 days', NOW(), '{"classification":"SECRET","domain":"signal","owner_org":"cyber"}'::jsonb),
    ('kl-sig-04', 'kl-cyd-001', 'kl-cl-02', 'multi_source_convergence',
     'AI-generated synthetic content narrative detected across 4 independent sources spanning official reports and social monitoring',
     '{"independent_source_count":4,"severity":"HIGH"}'::jsonb,
     'new', NOW()-INTERVAL '8 days', NOW(), '{"classification":"SECRET","domain":"signal","owner_org":"cyber"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ==========================================================================
-- 8. Keyword Alert Rules + Triggers
-- ==========================================================================
INSERT INTO keyword_alert_rules (id, topic_id, keywords, match_mode, is_active, notify_websocket, created_by, org_id, created_at, updated_at, labels) VALUES
    ('kl-alert-01', 'kl-cyd-001', ARRAY['grooming', 'sextortion', 'exploitation', 'predator', 'POCSO'], 'any', true, true, 'ec-user-cyber', 'org_cyber', NOW()-INTERVAL '25 days', NOW(), '{"classification":"SECRET","domain":"alert","owner_org":"cyber"}'::jsonb),
    ('kl-alert-02', 'kl-cyd-001', ARRAY['deepfake', 'synthetic', 'AI-generated', 'face-swap', 'DIRE'], 'any', true, true, 'ec-user-cyber', 'org_cyber', NOW()-INTERVAL '25 days', NOW(), '{"classification":"SECRET","domain":"alert","owner_org":"cyber"}'::jsonb),
    ('kl-alert-03', 'kl-cyd-001', ARRAY['crypto wallet', 'Monero', 'Bitcoin', 'UPI mule', 'hawala'], 'any', true, true, 'ec-user-cyber', 'org_cyber', NOW()-INTERVAL '25 days', NOW(), '{"classification":"SECRET","domain":"alert","owner_org":"cyber"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO keyword_alert_triggers (id, rule_id, content_item_id, matched_keywords, triggered_at, labels) VALUES
    ('kl-trig-01', 'kl-alert-01', 'kl-ci-01', ARRAY['predator'], NOW()-INTERVAL '28 days', '{"classification":"SECRET","domain":"alert","owner_org":"cyber"}'::jsonb),
    ('kl-trig-02', 'kl-alert-01', 'kl-ci-04', ARRAY['sextortion'], NOW()-INTERVAL '24 days', '{"classification":"SECRET","domain":"alert","owner_org":"cyber"}'::jsonb),
    ('kl-trig-03', 'kl-alert-01', 'kl-ci-07', ARRAY['grooming','POCSO'], NOW()-INTERVAL '18 days', '{"classification":"SECRET","domain":"alert","owner_org":"cyber"}'::jsonb),
    ('kl-trig-04', 'kl-alert-02', 'kl-ci-16', ARRAY['deepfake','sextortion'], NOW()-INTERVAL '20 days', '{"classification":"SECRET","domain":"alert","owner_org":"cyber"}'::jsonb),
    ('kl-trig-05', 'kl-alert-02', 'kl-ci-18', ARRAY['deepfake','DIRE'], NOW()-INTERVAL '16 days', '{"classification":"SECRET","domain":"alert","owner_org":"cyber"}'::jsonb),
    ('kl-trig-06', 'kl-alert-03', 'kl-ci-24', ARRAY['Bitcoin','crypto wallet'], NOW()-INTERVAL '23 days', '{"classification":"SECRET","domain":"alert","owner_org":"cyber"}'::jsonb),
    ('kl-trig-07', 'kl-alert-03', 'kl-ci-26', ARRAY['Monero','Bitcoin','UPI mule'], NOW()-INTERVAL '18 days', '{"classification":"SECRET","domain":"alert","owner_org":"cyber"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ==========================================================================
-- 9. Forwarding Chains (for network graph)
-- ==========================================================================
-- @online_safety_watch_in forwards FROM @cybercrime_alert_kl
UPDATE content_items SET forwarded_from_channel_name = 'cybercrime_alert_kl' WHERE id IN ('kl-ci-03', 'kl-ci-27', 'kl-ci-36');
-- @pocso_tracker_kl forwards FROM @online_safety_watch_in
UPDATE content_items SET forwarded_from_channel_name = 'online_safety_watch_in' WHERE id IN ('kl-ci-06', 'kl-ci-19', 'kl-ci-29');
-- @pocso_tracker_kl forwards FROM @cybercrime_alert_kl
UPDATE content_items SET forwarded_from_channel_name = 'cybercrime_alert_kl' WHERE id IN ('kl-ci-38');

-- ==========================================================================
-- Done. Verify counts:
-- ==========================================================================
SELECT 'Topics' AS entity, COUNT(*) FROM topics WHERE id = 'kl-cyd-001'
UNION ALL SELECT 'Sources', COUNT(*) FROM sources WHERE id LIKE 'kl-src-%'
UNION ALL SELECT 'Content Items', COUNT(*) FROM content_items WHERE id LIKE 'kl-ci-%'
UNION ALL SELECT 'Clusters', COUNT(*) FROM narrative_clusters WHERE id LIKE 'kl-cl-%'
UNION ALL SELECT 'Entities', COUNT(*) FROM extracted_entities WHERE id LIKE 'kl-ent-%'
UNION ALL SELECT 'ID Clusters', COUNT(*) FROM identifier_clusters WHERE id LIKE 'kl-ic-%'
UNION ALL SELECT 'Signals', COUNT(*) FROM signals WHERE id LIKE 'kl-sig-%'
UNION ALL SELECT 'Alert Rules', COUNT(*) FROM keyword_alert_rules WHERE id LIKE 'kl-alert-%'
UNION ALL SELECT 'Alert Triggers', COUNT(*) FROM keyword_alert_triggers WHERE id LIKE 'kl-trig-%';
